apiVersion: v2
name: regression-logging
description: Helm chart for regression logging and visualization
type: application

version: 0.1.0

appVersion: "0.1.0"
maintainers:
  - name: khsa1
dependencies:
  - name: database
    version: 0.19.5
    repository: https://osc.github.io/osc-helm-charts
  - name: osc-common
    version: 0.17.0
    repository: https://osc.github.io/osc-helm-charts
    condition: osc-common.enabled
