apiVersion: v2
name: kyverno-policies
description: OSC Kyverno policies deployment
type: application
version: 0.2.0
appVersion: "v1.5.0"
maintainers:
  - name: treydock
dependencies:
  - name: kyverno-policies
    version: v2.1.1
    repository: https://kyverno.github.io/kyverno/
