apiVersion: v2
name: kyverno-policies
description: OSC Kyverno policies deployment
type: application
version: 0.22.0
appVersion: "v1.9.5"
maintainers:
  - name: treydock
dependencies:
  - name: kyverno-policies
    version: 2.7.5
    repository: https://kyverno.github.io/kyverno/
