kyverno-policies:
  # Supported- baseline/restricted/privileged/custom
  # For more info- https://kyverno.io/policies/pod-security
  podSecurityStandard: custom
  # Policies to include when podSecurityStandard is custom
  podSecurityPolicies:
    - disallow-add-capabilities
    - disallow-host-namespaces
    - disallow-host-ports
    - disallow-privileged-containers
    - require-default-proc-mount
    - disallow-selinux
    - restrict-apparmor-profiles
    - deny-privilege-escalation
    - require-run-as-non-root
    - restrict-seccomp
    - restrict-sysctls
    # Can not use as OnDemand uses HostPath, custom policy in this repo
    # - disallow-host-path
    # Need to allow supplementalGroups for OnDemand
    # - require-non-root-groups
    # Omit for now
    # - restrict-volume-types
  # Supported- low/medium/high
  podSecuritySeverity: medium
  # Supported values- `audit`, `enforce`
  # For more info- https://kyverno.io/docs/writing-policies/validate/
  validationFailureAction: enforce

  nameOverride:
  # -- Additional labels
  customLabels: {}
