users:
  # -- Allowed host paths for user namespaces
  allowHostPaths:
    - /var/lib/sss/pipes
    - /etc/sssd
    - /etc/nsswitch.conf
    - /etc/pam.d
    - /etc/slurm
    - /var/run/munge/munge.socket.2
    - /users/?*
    - /fs/?*
    - /apps/?*
    - /nfsroot/?*
  # -- Authorized registries for user namespaces
  authorizedRegistries:
    - docker-registry.osc.edu
    - docker-registry-test.osc.edu
webservices:
  # -- Allowed host paths for webservices
  allowHostPaths:
    - /var/lib/sss/pipes
    - /etc/sssd
    - /etc/nsswitch.conf
    - /etc/slurm
    - /var/run/munge/munge.socket.2
    - /users/?*
    - /fs/?*
  # -- Authorized registries for webservices
  authorizedRegistries:
    - docker-registry.osc.edu
    - docker-registry-test.osc.edu
    - quay.io/oauth2-proxy/oauth2-proxy
  # -- Allowed node selectors for webservices
  validNodeSelector:
    - infrastructure
    - webservices
  # -- Allowed storage classes for webservices
  validStorageClass:
    - local-ess
    - local-path
    - webservices-nfs-client
paas:
  # -- Allowed host paths for PAAS namespaces
  allowHostPaths:
    - /var/lib/sss/pipes
    - /etc/sssd
    - /etc/nsswitch.conf
    - /etc/slurm
    - /var/run/munge/munge.socket.2
    - /users/?*
    - /fs/?*
  # -- Authorized registries for PAAS namespaces
  authorizedRegistries:
    - docker-registry.osc.edu
    - docker-registry-test.osc.edu
    - quay.io/oauth2-proxy/oauth2-proxy
  # -- Allowed node selectors for PAAS namespaces
  validNodeSelector:
    - paas
  # -- The cert-manager cluster issuer for PAAS namespaces
  certManagerClusterIssuer: letsencrypt
  # -- The Ingress class name for PAAS namespaces
  ingressClassName: nginx
  validStorageClass:
    # -- Allow storage classes for PAAS namespaces
    paas:
      - local-ess
    # -- Allowed storage classes for staff PAAS namespaces
    paasStaff:
      - local-ess
      - local-path
      - paas-nfs-client
kyverno-policies:
  # -- Pod Security Standard profile (`baseline`, `restricted`, `privileged`, `custom`).
  # For more info https://kyverno.io/policies/pod-security.
  podSecurityStandard: restricted
  # -- Additional policies to include from `other`.
  includeOtherPolicies:
    - require-non-root-groups
  # -- Pod Security Standard (`low`, `medium`, `high`).
  podSecuritySeverity: medium
  # -- Validation failure action (`Audit`, `Enforce`).
  # For more info https://kyverno.io/docs/policy-types/cluster-policy/validate.
  validationFailureAction: Enforce
#  validationFailureActionOverrides:
#    all:
#      - action: Audit
#        namespaces:
#          - external-dns
#          - prometheus
  # @ignored
  policyExclude:
    disallow-host-path:
      any:
        - resources:
            namespaces:
            - "user-?*"
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
                - paas
    restrict-volume-types:
      any:
        - resources:
            namespaces:
            - "user-?*"
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
                - paas
  # @ignored
  policyPreconditions:
    disallow-capabilities:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    disallow-capabilities-strict:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    disallow-privilege-escalation:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    disallow-host-path:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    require-run-as-non-root-user:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    require-run-as-nonroot:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    check-runasgroup:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    restrict-seccomp-strict:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
    restrict-volume-types:
      all:
        - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/name\" || '' }}"
          operator: NotEquals
          value: "dcgm-exporter"
  nameOverride:
  # -- Additional labels
  customLabels: {}
