users:
  allowHostPaths:
    - /var/lib/sss/pipes
    - /etc/sssd
    - /etc/nsswitch.conf
    - /etc/pam.d
    - /etc/slurm
    - /var/run/munge/munge.socket.2
    - /users/?*
    - /fs/?*
    - /apps/?*
    - /nfsroot/?*
  authorizedRegistries:
    - docker.io/ohiosupercomputer
webservices:
  allowHostPaths:
    - /etc/slurm
    - /var/run/munge/munge.socket.2
    - /users/?*
    - /fs/?*
  authorizedRegistries:
    - docker.io/ohiosupercomputer
    - quay.io/oauth2-proxy/oauth2-proxy
    - docker.io/bitnami/*-exporter
kyverno-policies:
  # Supported- baseline/restricted/privileged/custom
  # For more info- https://kyverno.io/policies/pod-security
  podSecurityStandard: restricted
  includeOtherPolicies:
    - require-non-root-groups
  # Supported- low/medium/high
  podSecuritySeverity: medium
  # Supported values- `audit`, `enforce`
  # For more info- https://kyverno.io/docs/writing-policies/validate/
  validationFailureAction: enforce
#  validationFailureActionOverrides:
#    all:
#      - action: audit
#        namespaces:
#          - external-dns
#          - prometheus
  policyExclude:
    disallow-capabilities:
      any:
        - resources:
            name: "dcgm-exporter*"
    disallow-capabilities-strict:
      any:
        - resources:
            name: "dcgm-exporter*"
        # TODO: Remove once ood_core updated
        # https://github.com/OSC/ood_core/pull/748
        - resources:
            namespaces:
            - "user-?*"
    disallow-privilege-escalation:
      any:
        - resources:
            name: "dcgm-exporter*"
    disallow-host-path:
      any:
        - resources:
            namespaces:
            - "user-?*"
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
        - resources:
            name: "dcgm-exporter*"
    require-run-as-non-root-user:
      any:
        - resources:
            name: "dcgm-exporter*"
    require-run-as-nonroot:
      any:
        - resources:
            name: "dcgm-exporter*"
    check-runasgroup:
      any:
        - resources:
            name: "dcgm-exporter*"
    restrict-seccomp-strict:
      any:
        - resources:
            name: "dcgm-exporter*"
        # TODO: Remove once ood_core updated
        # https://github.com/OSC/ood_core/pull/748
        - resources:
            namespaces:
            - "user-?*"
    restrict-volume-types:
      any:
        - resources:
            namespaces:
            - "user-?*"
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
        - resources:
            name: "dcgm-exporter*"

  nameOverride:
  # -- Additional labels
  customLabels: {}
