global:
  environment: ""
  imageTag: v0.1.0
  oscServiceAccount: emthub
  env:
    production:
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    test:
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    dev:
      replicas: 1
      image:
        tag: latest
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      maintenance:
        groups:
          - wiagstf
webservice:
  appType: rshiny
  auth:
    enable: false
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/emthub
  mounts:
    roDir:
      project: /fs/ess/PAS2531
  service:
    alert:
      receiver: gateways
  debugGroups:
    - wiagstf
