global:
  # -- The service account used by OSC deployments.
  # Also pulled from global.env.<env>.serviceAccount
  oscServiceAccount: ""
  # -- The deployment's OSC environment
  environment: production
  # -- The nodeSelector role
  nodeSelectorRole: webservices
  imagePullSecret:
    # -- Create the image pull secret
    create: true
    # -- image pull secret name
    name: osc-registry
    # -- OSC registry address
    registry: docker-registry.osc.edu
    # -- The image pull secret password for database images
    # @default -- **required**
    password:
  networkPolicy:
    # -- Create the network policy
    create: false
    # -- Labels for NetworkPolicy podSelector. Defaults to `"osc.common.selectorLabels"`
    podSelector: ~
    # Example define podSelector labels
    #  podSelector:
    #    app.kubernetes.io/name: test
    #
    # -- Labels of pods allowed to Ingress from the same namespace
    ingressAllowedPods: []
    # Example additional ingress labels
    #  ingressAllowedPods:
    #    - require: test
    #    - client: test
    #
    # @ignored
    ingressNamespace: ingress-nginx
    # @ignored
    prometheusNamespace: prometheus
  # -- Groups that debug pods
  debugGroups: []
  # -- Groups that can perform maintenance operations
  maintenanceGroups: []
  # -- Groups that are allowed to perform port forwarding
  portforwardGroups: []
  webservicesDeploy:
    # -- Create webservices deployment rolebinding
    create: true
  ingress:
    # -- Ingress host
    # @default -- **required**
    host: ""
    # -- Ingress host alias
    # @default -- **required**
    hostAlias: ""
    # -- Additional Ingress annotations for the Ingress resource
    annotations: ~
  auth:
    # @ignored
    enable: false
    # @ignored
    keycloakClient:
      forceCreate: true
      # Set secret name to ensure rendered the same for osc-common and dependenc open-webui chart
      # @ignored
      secret:
        name: "{{ .Release.Name }}-auth-secret"
      # Set configmap name to ensure rendered the same for osc-common and dependenc open-webui chart
      # @ignored
      configmap:
        name: "{{ .Release.Name }}-auth-config"
    # -- Restrict access to these groups
    allowGroups: []
  alert:
    # -- The alert receiver
    receiver:
  # The Open WebUI secret key
  # @default -- **required**
  webui_secret_key:

# TODO - Remove
auth:
  enable: false

ollama:
  networkPolicy:
    # -- Array of additional pod labels to allow
    allowedPodLabels: []

open-webui:
  # @ignored
  nameOverride: open-webui
  # @ignored
  openaiApiKey: false
  # @ignored
  pipelines:
    enabled: false
  # @ignored
  websocket:
    enabled: false
  # @ignored
  extraLabels:
    '{{ include "osc.common.serviceAccountKey" . }}': '{{ include "osc.common.serviceAccountValue" . }}'
    receiver: '{{ .Values.global.alert.receiver }}'
  # @ignored
  podLabels:
    '{{ include "osc.common.serviceAccountKey" . }}': '{{ include "osc.common.serviceAccountValue" . }}'
    receiver: '{{ .Values.global.alert.receiver }}'
  image:
    # -- OSC registry location for Open WebUI image
    repository: docker-registry.osc.edu/kubernetes/open-webui/open-webui
    # Use custom build until released:
    # https://github.com/open-webui/open-webui/commit/6d7744c21903ec5a9ad951770dea76e9ba19cbcc
    # tag: '0.8.8'
    # -- The Open WebUI image tag.  Must be synced to OSC registry
    tag: 0.8.9-osc-r1
  # @ignored
  imagePullSecrets:
    - name: '{{ .Values.global.imagePullSecret.name }}'
  resources:
    limits:
      # -- Open WebUI pod memory limit
      memory: 4Gi
      # -- Open WebUI pod CPU limit
      cpu: 2
    requests:
      # -- Open WebUI pod memory request
      memory: 2Gi
      # -- Open WebUI pod CPU request
      cpu: 1
  # @ignored
  copyAppData:
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        memory: 500Mi
        cpu: 500m
  # @ignored
  ingress:
    enabled: false
  persistence:
    # @ignored
    size: 10Gi
    # -- The Open WebUI persistent storage class
    storageClass: webservices-nfs-client
  # @ignored
  nodeSelector:
    '{{ include "osc.common.nodeSelectorRoleKey" . }}': ''
  # -- Additional Open WebUI environment variables
  extraEnvVars: []
  # @ignored
  commonEnvVars:
    - name: ENABLE_OAUTH_GROUP_CREATION
      value: "True"
    - name: DEFAULT_USER_ROLE
      value: user
    - name: ENABLE_SIGNUP
      value: "True"
    - name: ENABLE_OAUTH_SIGNUP
      value: "True"
    - name: ENABLE_LOGIN_FORM
      value: "False"
    - name: WEBUI_AUTH
      value: "True"
    - name: ENABLE_VERSION_UPDATE_CHECK
      value: "False"
    - name: ENABLE_API_KEYS
      value: "True"
    - name: USER_PERMISSIONS_FEATURES_API_KEYS
      value: "True"
  # @ignored
  extraEnvFrom:
    - secretRef:
        name: osc-open-webui-secret
  # @ignored
  service:
    port: 80
    labels:
      receiver: '{{ .Values.global.alert.receiver }}'
    annotations:
      prometheus.io/probe_module: http
      prometheus.io/probe_scheme: http
  # @ignored
  podSecurityContext:
    runAsNonRoot: true
  # @ignored
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
  sso:
    # @ignored
    enabled: true
    # @ignored
    mergeAccountsByEmail: true
    # -- Enables role access controls in Open WebUI
    enableRoleManagement: true
    # @ignored
    enableGroupManagement: true
    # @ignored
    oidc:
      enabled: true
      clientExistingSecret: '{{ tpl .Values.global.auth.keycloakClient.secret.name . }}'
      clientIdExistingSecretKey: client-id
      clientExistingSecretKey: client-secret
      existingConfig: '{{ tpl .Values.global.auth.keycloakClient.configmap.name . }}'
      existingConfigProviderUrlKey: PROVIDER_URL
      providerName: "OSC SSO"
      scopes: "openid email profile groups basic osc-oidc-clients"
    # @ignored
    roleManagement:
      rolesClaim: groups
      allowedRoles: '{{ join "," .Values.global.allowGroups }}'
      adminRoles: sysstf,sappstf
    # @ignored
    trustedHeader:
      enabled: false
  ollama:
    # Added so can be referenced
    nameOverride: ollama
    image:
      repository: docker-registry.osc.edu/kubernetes/ollama/ollama
      tag: '0.16.1'
    imagePullSecrets:
      - name: osc-registry
    ollama:
      gpu:
        enabled: true
        type: nvidia
        number: 1
    nodeSelector: {}
    # Example using MIG product
    # nodeSelector:
    #   nvidia.com/gpu.product: NVIDIA-A100-PCIE-40GB-MIG-7g.40gb
    #   node-role.kubernetes.io/webservices: ''
    service:
      annotations:
        prometheus.io/probe_module: http
        prometheus.io/probe_scheme: http
    deployment:
      labels: {}
      # Example labels
      # labels:
      #   osc.edu/service-account: TODO
    podLabels: {}
    # Example labels
    # podLabels:
    #   osc.edu/service-account: TODO
    podSecurityContext:
      runAsNonRoot: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
      privileged: false
    resources:
      limits:
        memory: 16Gi
        cpu: 8
      requests:
        memory: 4Gi
        cpu: 2
    # @ignored
    initContainers:
      - name: create-dirs
        image: docker-registry.osc.edu/kubernetes/busybox:latest
        imagePullPolicy: Always
        command: ['sh', '-c', 'mkdir -p /data/ollama-models /home/ollama/ollama-home']
        volumeMounts:
          - name: data
            mountPath: /data
          - name: home
            mountPath: /home/ollama
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 265Mi
            cpu: 200m
    volumes: []
    # Example ESS mount
    # volumes:
    # - name: data
    #   hostPath:
    #     path: /fs/ess/TODO
    #     type: Directory
    # - name: home
    #   hostPath:
    #     path: /users/PROJECT/USER
    #     type: Directory
    volumeMounts:
      - name: data
        mountPath: /data
        subPath: ollama-models
      - name: home
        mountPath: /home/ollama
        subPath: ollama-home
    extraEnv:
      - name: OLLAMA_MODELS
        value: /data
      - name: HOME
        value: /home/ollama
      - name: OLLAMA_FLASH_ATTENTION
        value: '1'
