apiVersion: v2
name: webservice
description: OSC webservice bootstrap Helm Chart
type: application
version: 0.28.0
appVersion: "0.1.0"
maintainers:
  - name: treydock
dependencies:
  - name: database
    version: 0.9.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../database
    condition: database.mariadb.enable, database.postgresql.enable
  - name: osc-common
    version: 0.5.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../common
