global:
  imagePullSecret:
    # @ignored
    name: osc-registry
    # @ignored
    registry: docker-registry.osc.edu
    # @ignored
    username: robot$webservices-read
    # -- Password for the robot account.
    # @section -- Image Config
    # @default -- **required**
    password:
  # -- The nodeSelector role
  nodeSelectorRole: webservices
  # -- The persistent storage class
  storageClass: webservices-nfs-client
  auth:
    # -- Enable auth management
    # @section -- Authentication
    enable: true
    # -- The upstream service for the OAuth2 proxy. **required** when auth is enabled
    # @section -- Authentication
    upstream: 'http://{{ include "webservice.name" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .Values.global.service.port }}'
    # -- Routes to skip auth
    # @section -- Authentication
    skipAuthRoutes: []
    # -- Restrict access to these groups
    # @section -- Authentication
    allowGroups: []
    # -- Common groups to allow
    # @section -- Authentication
    commonAllowGroups:
      - sysstf
  ingress:
    # -- Ingress host
    # @section -- Ingress
    # @default -- **required**
    host: ""
    # -- Ingress host alias
    # @section -- Ingress
    # @default -- **required**
    hostAlias: ""
  # -- Groups that debug pods
  # @section -- Extra RBAC
  debugGroups: []
  # -- Groups that can perform maintenance operations
  # @section -- Extra RBAC
  maintenanceGroups: []
  alert:
    # -- The alert receiver name. Also pulled from global.env.$environment.alert.receiver
    # @section - Monitoring
    receiver: ""
  service:
    # -- Service port
    # @section -- App Config
    port: 3000

# -- The application type
# @section -- App Config
appType: rails
# -- Command to start webservice
# @section -- App Config
# @default -- Pulled from `defaultCommand`
command: []
# -- Args to start webservice
# @section -- App Config
# @default -- Pulled from `defaultArgs`
args: []
# -- webservice working directory
# @section -- App Config
workingDir:
# -- List environment variables, eg: `{"name": "<name>", "value": "<value>"}`
# @section -- App Config
env: []
defaultCommand:
  # -- Default command when `appType` is `rails`
  # @section -- App Config
  # @default -- Command for Rails
  rails: ['bundle', 'exec', 'passenger', 'start']
  # -- Default command when `appType` is `rshiny`
  # @section -- App Config
  # @default -- Command for RShiny
  rshiny: ['/bin/passenger', 'start']
  # -- Default command when `appType` is `none`
  # @section -- App Config
  none: []
defaultArgs:
  # -- Default args when `appType` is `rails`
  # @section -- App Config
  # @default -- Rails args
  rails:
    # Set by PASSENGER_PORT env var
    # - "--port={{ .Values.service.port }}"
    - "--min-instances=1"
    - "--sticky-sessions"
    - "--start-timeout=180"
    - "--environment=production"
    - "--disable-security-update-check"
    - "--disable-anonymous-telemetry"
    - "--log-file=/dev/stdout"
    - "--pid-file=/tmp/passenger-{{ .name }}.pid"
  # -- Default args when `appType` is `rshiny`
  # @section -- App Config
  # @default -- RShiny args
  rshiny:
    # Set by PASSENGER_PORT env var
    # - "--port={{ .Values.service.port }}"
    - "--min-instances=1"
    - "--sticky-sessions"
    - "--start-timeout=180"
    - "--environment=production"
    - "--disable-security-update-check"
    - "--disable-anonymous-telemetry"
    - "--log-file=/dev/stdout"
    - "--pid-file=/tmp/passenger-{{ .name }}.pid"
    - "--app-start-command"
    - '{{ .startCommand | default "R --no-save --slave -f /app/entrypoint.R --args $$PORT" }}'
  # -- Default args when `appType` is `none`
  # @section -- App Config
  none: []
# -- Containers used to run the web service
# @section -- App Config
# @default -- A single container
containers:
  - name: '{{ include "webservice.name" . }}'
    port: ~
    portName: http
    startCommand: ~
    probePath: ~
    probeType: ~
    ingressPath: /

image:
  # -- Image repository.
  # @section -- Image Config
  # @default -- **required**
  repository:
  # -- Image tag. Also pulled from `global.env.<env>.image.tag`.
  # @section -- Image Config
  # @default -- **required**
  tag:
  # -- imagePullPolicy.  **Forced to `Always` when image tag contains `:latest`**.
  # @section -- Image Config
  pullPolicy: IfNotPresent

mounts:
  # -- emptyDir mounts
  # @section -- Mounts
  emptyDir: {}
  # -- webservice home mount that is mounted at same location inside pod
  # @section -- Mounts
  home: ''
  # -- Read-only directory volumes, `name: path`.
  # @section -- Mounts
  roDir: {}
  # -- Read-write directory volumes, `name: path`.
  # @section -- Mounts
  rwDir: {}
  # -- Socket volumes, `name: path`.
  # @section -- Mounts
  socket: {}
  # -- Read-only file volumes, `name: path`.
  # @section -- Mounts
  roFile: {}

# -- Additional nodeSelector that is added to existing role selection.
nodeSelector: {}

# @ignored
podSecurityContext:
  runAsNonRoot: true

podResources:
  limits:
    # -- The pod CPU limits
    cpu: 4
    # -- The pod memory limits
    memory: 4Gi
  requests:
    # -- The pod CPU request
    cpu: 1
    # -- The pod memory request
    memory: 256Mi

# -- Number of replicas. Also pulled from `global.env.<env>.replicas`
# @default -- 1
replicas:

# @ignored
podDistributionBudget:
  minAvailable: 1

# -- Secrets for this webservice, eg `{"name": "value"}`
secrets: {}
# -- Environment secrets for this webservice, eg `{"NAME": "value"}`
envSecrets: {}

service:
  # -- Additional service annotations
  annotations: {}
  typeAnnotations:
    # -- Default Service annotations when `appType` is `rshiny`
    # @default -- Specific to rshiny
    rshiny:
      prometheus.io/probe_module: http
      prometheus.io/probe_scheme: http

probes:
  # -- Type of probes to use, eg `httpGet` or `tcpSocket`
  # @default -- `httpGet`
  type: ~
  # -- Default probe path for probes
  path: /
  typeDefaults:
    # -- Type of probes to use when `appType` is `rshiny`.
    rshiny: tcpSocket
startupProbe:
  httpGet:
    # -- Config for httpGet startupProbe path
    # @default -- container `probePath` or `probes.path`
    path: '{{ .probePath | default .Values.probes.path }}'
    # -- Config for httpGet startupProbe port
    # @default -- container `portName` or container `name`
    port: '{{ .portName | default .name }}'
  # -- Config for tcpSocket startupProbe
  # @default -- container `portName` or container `name`
  tcpSocket:
    port: '{{ .portName | default .name }}'
  # -- startupProbe failureThreshold
  failureThreshold: 12
  # -- startupProbe periodSeconds
  periodSeconds: 10
  # -- startupProbe timeoutSeconds
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    # -- Config for httpGet livenessProbe path
    # @default -- container `probePath` or `probes.path`
    path: '{{ .probePath | default .Values.probes.path }}'
    # -- Config for httpGet livenessProbe port
    # @default -- container `portName` or container `name`
    port: '{{ .portName | default .name }}'
  # -- Config for tcpSocket livenessProbe
  # @default -- container `portName` or container `name`
  tcpSocket:
    port: '{{ .portName | default .name }}'
  # -- livenessProbe failureThreshold
  failureThreshold: 6
  # -- livenessProbe periodSeconds
  periodSeconds: 10
  # -- livenessProbe timeoutSeconds
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    # -- Config for httpGet readinessProbe path
    # @default -- container `probePath` or `probes.path`
    path: '{{ .probePath | default .Values.probes.path }}'
    # -- Config for httpGet readinessProbe port
    # @default -- container `portName` or container `name`
    port: '{{ .portName | default .name }}'
  # -- Config for tcpSocket readinessProbe
  # @default -- container `portName` or container `name`
  tcpSocket:
    port: '{{ .portName | default .name }}'
  # -- readinessProbe failureThreshold
  failureThreshold: 6
  # -- readinessProbe periodSeconds
  periodSeconds: 10
  # -- readinessProbe timeoutSeconds
  timeoutSeconds: 5

# -- webservice init containers
initContainers: {}
init:
  podResources:
    limits:
      # -- init container pod CPU limits
      cpu: 1
      # -- init container pod memory limits
      memory: 1Gi
    requests:
      # -- init container pod CPU request
      cpu: 200m
      # -- init container pod memory request
      memory: 256Mi

# @ignored
ingress:
  # @ignored
  className: "nginx"
  # @ignored
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  # @ignored
  rShinyAnnotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
     location / {
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $connection_upgrade;
       proxy_buffering off;
      }

data:
  # -- Enable use of persistent data volume
  enable: false
  # @ignored
  storageClass: '{{ .Values.global.storageClass }}'
  # -- Persistent data volume size
  storageSize: 10Gi
  # -- Persistent data volume mount path
  path: /data

database:
  # -- Enable database subchart
  # @section -- Database
  enable: false
  # @ignored
  imagePullSecret:
    enable: false
  mariadb:
    # -- Enable MariaDB database
    # @section -- Database
    enable: false
    auth:
      # -- The root user admin password
      # @section -- Database
      # @default -- **required**
      rootPassword:
      # -- The database name
      # @section -- Database
      # @default -- **required**
      database:
      # -- The database username
      # @section -- Database
      # @default -- **required**
      username:
      # -- The database password
      # @section -- Database
      # @default -- **required**
      password:
    # @ignored
    networkPolicy:
      ingressRules:
        primaryAccessOnlyFrom:
          podSelector:
            app.kubernetes.io/name: '{{ include "webservice.name" . }}'
  postgresql:
    # -- Enable PostgreSQL database
    # @section -- Database
    enable: false
    auth:
      # -- The postgres user admin password
      # @section -- Database
      # @default -- **required**
      postgresPassword:
      # -- The database name
      # @section -- Database
      # @default -- **required**
      database:
      # -- The database username
      # @section -- Database
      # @default -- **required**
      username:
      # -- The database password
      # @section -- Database
      # @default -- **required**
      password:
    # @ignored
    networkPolicy:
      ingressRules:
        primaryAccessOnlyFrom:
          podSelector:
            app.kubernetes.io/name: '{{ include "webservice.name" . }}'
# @ignored
hook:
  image:
    repository: docker-registry.osc.edu/kubernetes/portainer/kubectl-shell
    tag: '2.39.0'
