global:
  imagePullSecret:
    # @ignored
    name: osc-registry
    # -- OSC container registry
    registry: docker-registry.osc.edu
    # -- OSC container registry robot account
    username: robot$webservices-read
    # -- Password for the robot account.
    # @default -- **required**
    password:
  # -- The nodeSelector role
  nodeSelectorRole: webservices
  # -- The persistent storage class
  storageClass: webservices-nfs-client
  auth:
    # -- Enable auth management
    enable: true
    # -- The upstream service for the OAuth2 proxy. **required** when auth is enabled
    upstream: 'http://{{ include "webservice.name" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ .Values.global.service.port }}'
    # -- Routes to skip auth
    skipAuthRoutes: []
    # -- Restrict access to these groups
    allowGroups: []
    # -- Common groups to allow
    commonAllowGroups:
      - sysstf
  ingress:
    # -- Ingress host
    host: ""
    # -- Ingress host alias
    hostAlias: ""
  # -- Groups that debug pods
  debugGroups: []
  # -- Groups that can perform maintenance operations
  maintenanceGroups: []
  alert:
    # -- The alert receiver name. Also pulled from global.env.$environment.alert.receiver
    receiver: ""
  service:
    # -- Service port
    port: 3000

appType: rails
# -- Command to start webservice
command: []
# -- Args to start webservice
args: []
# -- webservice working directory
workingDir:
# -- List environment variables, eg: `{"name": "<name>", "value": "<value>"}`
env: []
defaultCommand:
  # -- Default command when `appType` is `rails`
  rails: ['bundle', 'exec', 'passenger', 'start']
  # -- Default command when `appType` is `rshiny`
  rshiny: ['/bin/passenger', 'start']
  # -- Default command when `appType` is `none`
  none: []
defaultArgs:
  # -- Default args when `appType` is `rails`
  rails:
    # Set by PASSENGER_PORT env var
    # - "--port={{ .Values.service.port }}"
    - "--min-instances=1"
    - "--sticky-sessions"
    - "--start-timeout=180"
    - "--environment=production"
    - "--disable-security-update-check"
    - "--disable-anonymous-telemetry"
    - "--log-file=/dev/stdout"
    - "--pid-file=/tmp/passenger-{{ .name }}.pid"
  # -- Default args when `appType` is `rshiny`
  rshiny:
    # Set by PASSENGER_PORT env var
    # - "--port={{ .Values.service.port }}"
    - "--min-instances=1"
    - "--sticky-sessions"
    - "--start-timeout=180"
    - "--environment=production"
    - "--disable-security-update-check"
    - "--disable-anonymous-telemetry"
    - "--log-file=/dev/stdout"
    - "--pid-file=/tmp/passenger-{{ .name }}.pid"
    - "--app-start-command"
    - '{{ .startCommand | default "R --no-save --slave -f /app/entrypoint.R --args $$PORT" }}'
  # -- Default args when `appType` is `none`
  none: []
containers:
  - name: '{{ include "webservice.name" . }}'
    port: ~
    portName: http
    startCommand: ~
    probePath: ~
    probeType: ~
    ingressPath: /

image:
  # -- Image repository.
  # @default -- **required**
  repository:
  # -- Image tag. Also pulled from `global.env.<env>.image.tag`.
  # @default -- **required**
  tag:
  # -- imagePullPolicy.  **Forced to `Always` when image tag contains `:latest`**.
  pullPolicy: IfNotPresent

mounts:
  emptyDir: {}
  # -- webservice home mount that is mounted at same location inside pod
  home: ''
  # -- Read-only directory volumes, `name=path`.
  roDir: {}
  # -- Read-write directory volumes, `name=path`.
  rwDir: {}
  # -- Socket volumes, `name=path`.
  socket: {}
  # -- Read-only file volumes, `name=path`.
  roFile: {}

# -- Additional nodeSelector that is added to existing role selection.
nodeSelector: {}

# @ignored
podSecurityContext:
  runAsNonRoot: true

# -- The pod resource limits
podResources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 1
    memory: 256Mi

# -- Number of replicas. Also pulled from `global.env.<env>.replicas`
# @default -- 1
replicas:

# @ignored
podDistributionBudget:
  minAvailable: 1

# -- Secrets for this webservice, eg `{"name": "value"}`
secrets: {}
# -- Environment secrets for this webservice, eg `{"NAME": "value"}`
envSecrets: {}

service:
  annotations: {}
  typeAnnotations:
    # -- Default Service annotations when `appType` is `rshiny`
    rshiny:
      prometheus.io/probe_module: http
      prometheus.io/probe_scheme: http

probes:
  # -- Type of probes to use, eg `httpGet` or `tcpSocket`
  # @default -- httpGet
  type: ~
  path: /
  typeDefaults:
    # -- Type of probes to use when `appType` is `rshiny`.
    rshiny: tcpSocket
startupProbe:
  # -- Config for httpGet startupProbe
  httpGet:
    path: '{{ .probePath | default .Values.probes.path }}'
    port: '{{ .portName | default .name }}'
  # -- Config for tcpSocket startupProbe
  tcpSocket:
    port: '{{ .portName | default .name }}'
  # -- startupProbe failureThreshold
  failureThreshold: 12
  # -- startupProbe periodSeconds
  periodSeconds: 10
  # -- startupProbe timeoutSeconds
  timeoutSeconds: 5
livenessProbe:
  # -- Config for httpGet livenessProbe
  httpGet:
    path: '{{ .probePath | default .Values.probes.path }}'
    port: '{{ .portName | default .name }}'
  # -- Config for tcpSocket livenessProbe
  tcpSocket:
    port: '{{ .portName | default .name }}'
  # -- livenessProbe failureThreshold
  failureThreshold: 6
  # -- livenessProbe periodSeconds
  periodSeconds: 10
  # -- livenessProbe timeoutSeconds
  timeoutSeconds: 5
readinessProbe:
  # -- Config for httpGet readinessProbe
  httpGet:
    path: '{{ .probePath | default .Values.probes.path }}'
    port: '{{ .portName | default .name }}'
  # -- Config for tcpSocket readinessProbe
  tcpSocket:
    port: '{{ .portName | default .name }}'
  # -- readinessProbe failureThreshold
  failureThreshold: 6
  # -- readinessProbe periodSeconds
  periodSeconds: 10
  # -- readinessProbe timeoutSeconds
  timeoutSeconds: 5

# -- webservice init containers
initContainers: {}
init:
  # -- init container pod resource limits
  podResources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  # -- ingress annotations used when `appType` is `rshiny`
  rShinyAnnotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
     location / {
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $connection_upgrade;
       proxy_buffering off;
      }

data:
  # -- Enable use of persistent data volume
  enable: false
  # @ignored
  storageClass: '{{ .Values.global.storageClass }}'
  # -- Persistent data volume size
  storageSize: 10Gi
  # -- Persistent data volume mount path
  path: /data

database:
  # -- Enable database subchart
  enable: false
  # @ignored
  imagePullSecret:
    enable: false
  mariadb:
    # -- Enable MariaDB database
    enable: false
    auth:
      # -- The root user admin password
      # @default -- **required**
      rootPassword:
      # -- The database name
      # @default -- **required**
      database:
      # -- The database username
      # @default -- **required**
      username:
      # -- The database password
      # @default -- **required**
      password:
    # @ignored
    networkPolicy:
      ingressRules:
        primaryAccessOnlyFrom:
          podSelector:
            app.kubernetes.io/name: '{{ include "webservice.name" . }}'
  postgresql:
    # -- Enable PostgreSQL database
    enable: false
    auth:
      # -- The postgres user admin password
      # @default -- **required**
      postgresPassword:
      # -- The database name
      # @default -- **required**
      database:
      # -- The database username
      # @default -- **required**
      username:
      # -- The database password
      # @default -- **required**
      password:
    # @ignored
    networkPolicy:
      ingressRules:
        primaryAccessOnlyFrom:
          podSelector:
            app.kubernetes.io/name: '{{ include "webservice.name" . }}'
# @ignored
hook:
  image:
    repository: docker-registry.osc.edu/kubernetes/portainer/kubectl-shell
    tag: '2.39.0'
