apiVersion: v2
name: osc-chat
description: A Helm chart for the OSC Chat service

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"
maintainers:
  - name: khsa1
dependencies:
  - name: database
    version: 0.15.0
    repository: https://osc.github.io/osc-helm-charts
  - name: minio
    version: 17.0.21
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: minio.enable
  - name: qdrant
    version: 1.16.3
    repository: "https://qdrant.github.io/qdrant-helm"
    condition: qdrant.enable
  - name: rabbitmq
    version: 16.0.14
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: rabbitmq.enable
  - name: osc-common
    version: 0.14.1
    repository: https://osc.github.io/osc-helm-charts
  - name: vllm-stack
    version: 0.1.10
    repository: "https://vllm-project.github.io/production-stack"
