global:
  imageRegistry: docker-registry.osc.edu
  imagePullSecret:
    name: osc-registry
    # -- OSC registry password
    # @default -- **required**
    password:
  oscServiceAccount: osc-chat
  database:
    allowIngress: true
  security:
    allowInsecureImages: true
  storageClass: webservices-nfs-client
  webservicesDeploy:
    create: false
  auth:
    enable: false
    keycloakClient:
      forceCreate: true
  ingress:
    host: ""
    hostAlias: ""

serviceAccount:
  name:

database:
  postgresql:
    schema:
      enabled: false
    enable: true
    imagePullSecret:
      enable: false
    auth:
      postgresPassword: secret
      database: name
      username: name
      password: secret

  redis:
    enable: true
    auth:
      password: secret

minio:
  enable: true
  image:
    repository: kubernetes/bitnami/minio
    tag: 2025.7.23-debian-12-r5
  defaultBuckets: "osc-chat"
  clientImage:
    repository: kubernetes/bitnami/minio-client
    tag: 2025.7.21-debian-12-r3
  console:
    image:
      repository: kubernetes/bitnami/minio-object-browser
      tag: 2.0.2-debian-12-r3
  imagePullSecret:
    enable: false
  auth:
    rootUser: "minioadmin"
    rootPassword: "minioadmin"
  ingress:
    enabled: true
    className: "nginx"
    hostname: skhuvis-chat-minio.k8.osc.edu
    tls: true
    path: /
    pathType: Prefix
    secretName: "chat-minio"
    extraTls:
      - hosts:
          - skhuvis-chat-minio.k8.osc.edu
        secretName: chat-minio


qdrant:
  enable: true
  resources:
    limits:
      memory: 8Gi
    requests:
      memory: 8Gi
  storageClass:
  image:
    repository: docker-registry.osc.edu/kubernetes/qdrant/qdrant
    tag: v1.16.3
    useUnprivilegedImage: true
  persistence:
    storageClassName: local-path
  snapshotPersistence:
    enabled: true
    storageClassName: webservices-nfs-client
#  snapshotRestoration:
#    enabled: true

rabbitmq:
  enable: true
  image:
    repository: kubernetes/bitnami/rabbitmq
    tag: 4.1.3-debian-12-r1
  imagePullSecret:
    enable: false
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 500m
      memory: 512Mi
  auth:
    username: guest
    password: guest
  perisistence:
    enabled: false
  rbac:
    create: false

backend:
  enabled: true
  ingress:
    enabled: false
  image:
    repository: osc/hpcgpt_backend
    tag: v0.1.0
    pullPolicy: Always
  imagePullSecret:
    enable: false
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8001
  env:
    FLASK_ENV: production
    EMBEDDING_API_BASE: https://skhuvis-vllm.k8.osc.edu/v1
    EMBEDDING_MODEL: Qwen/Qwen3-Embedding-8B
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

worker:
  enabled: true
  image:
    repository: osc/hpcgpt_backend
    tag: v0.1.0
    pullPolicy: Always
  replicaCount: 1
  env:
    QDRANT_COLLECTION_NAME: '{{ include "osc-chat.name" . }}'
    S3_BUCKET_NAME: '{{ include "osc-chat.name" . }}'
    EMBEDDING_API_BASE: https://skhuvis-vllm.k8.osc.edu/v1
    EMBEDDING_MODEL: Qwen/Qwen3-Embedding-8B
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

ollama:
  enabled: false

huggingfaceCache:
  enabled: true
  mountPath: "/var/cache/huggingface"
  sizeLimit: "5Gi"
  storageClassName: paas-nfs-client

secrets:
  # Internal secrets - created by the chart
  create: true
  api:
    openaiKey: "your_strong_key"
    qdrantKey: "your_strong_key"

crawlee:
  enabled: true
  image:
    repository: osc/crawlee
    tag: v0.1.0
    pullPolicy: Always
  imagePullSecret:
    enable: false
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  env:
    NO_CRAWL: FALSE
    S3_BUCKET_NAME: osc-chat
    AWS_REGION: us-east-1
  probes:
    liveness:
      enabled: true
    readiness:
      enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi


keycloak:
  enabled: false

frontend:
  enabled: true
  image:
    repository: osc/hpcgpt_frontend
    tag: v0.1.0
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: skhuvis.k8.osc.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
        - skhuvis.k8.osc.edu
        secretName: osc-chat-frontend
  env:
    HOSTED_VLM_BASE_URL: https://skhuvis-vllm.k8.osc.edu/v1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

networkPolicies:
  enabled: false

vllm-stack:
  enabled: true
  servingEngineSpec:
    labels:
      release: osc-chat
    runtimeClassName: ""
    modelSpec:
    # Qwen Model
    - name: "qwen3"
      repository: "docker-registry.osc.edu/kubernetes/vllm/vllm-openai"
      tag: "v0.21.0"
      imagePullSecret: osc-registry
      modelURL: "Qwen/Qwen3-8B"
      replicaCount: 1
      enableLoRA: false

      requestCPU: 4
      requestMemory: "48Gi"
      requestGPU: 1
      limitCPU: 4
      limitMemory: "48Gi"
      limitGPU: 1

      podAnnotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8000'
      pvcStorage: "50Gi"
      pvcAccessMode:
        - ReadWriteMany
#        - ReadWriteOnce
      storageClass: local-ess
#      storageClass: local-path
#      pvcLabels:
#        osc.edu/service-account: skhuvis
      pvcAnnotations:
        osc.edu/fileset: PDE0050

      vllmConfig:
#        enableChunkedPrefill: false
#        enablePrefixCaching: false
        maxModelLen: 40960
        dtype: "half"
#        extraArgs: ["--disable-log-requests", "--gpu-memory-utilization", "0.50"]
#        extraArgs: ["--enforce-eager", "--quantization", "awq", "--gpu-memory-utilization", "0.85"]
        extraArgs:
          - "--disable-access-log-for-endpoints"
          - "/health,/metrics,/ping"
#          - "--enforce-eager"
          - "--gpu-memory-utilization"
          - "0.90"
          - "--served-model-name"
          - "Qwen/Qwen3-8B"
          - "--safetensors-load-strategy"
          - "eager"
          - "--max-num-seqs"
          - "128"
#          - '--distributed-executor-backend=ray'
#        extraArgs: ["--enforce-eager", "--quantization", "bitsandbytes", "--gpu-memory-utilization", "0.85"]
#        tensorParallelSize: 2
      enableTool: true
      toolCallParser: hermes

      nodeSelectorTerms:
      - matchExpressions:
        - key: nvidia.com/gpu.product
          operator: In
          values:
#          - NVIDIA-A100-PCIE-40GB-MIG-3g.20gb
          - NVIDIA-A100-PCIE-40GB-MIG-7g.40gb
#          - NVIDIA-A100-PCIE-40GB-MIG-1g.5gb
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - kubeworker27

#      keda:
#        enabled: false
#      lmcacheConfig:
#        enabled: false

#      hf_token: ""
    - name: "qwen3-embedding"
      repository: "docker-registry.osc.edu/kubernetes/vllm/vllm-openai"
      tag: "v0.21.0"
      imagePullSecret: osc-registry
      modelURL: "Qwen/Qwen3-Embedding-8B"
      replicaCount: 1
      enableLoRA: false

      requestCPU: 4
      requestMemory: "36Gi"
      requestGPU: 1
      limitCPU: 4
      limitMemory: "36Gi"
      limitGPU: 1

      podAnnotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8000'
      pvcStorage: "50Gi"
      pvcAccessMode:
        - ReadWriteMany
      storageClass: local-ess
      pvcLabels:
        osc.edu/service-account: osc-chat
      pvcAnnotations:
        osc.edu/fileset: PDE0050

      vllmConfig:
#        enableChunkedPrefill: false
#        enablePrefixCaching: false
        maxModelLen: 40960
        dtype: "half"
#        extraArgs: ["--disable-log-requests", "--gpu-memory-utilization", "0.50"]
#        extraArgs: ["--enforce-eager", "--quantization", "awq", "--gpu-memory-utilization", "0.85"]
        extraArgs:
          - "--disable-access-log-for-endpoints"
          - "/health,/metrics,/ping"
#          - "--enforce-eager"
          - "--gpu-memory-utilization"
          - "0.90"
          - "--served-model-name"
          - "Qwen/Qwen3-Embedding-8B"
          - "--safetensors-load-strategy"
          - "eager"
          - "--max-num-seqs"
          - "128"
#          - '--distributed-executor-backend=ray'
#        extraArgs: ["--enforce-eager", "--quantization", "bitsandbytes", "--gpu-memory-utilization", "0.85"]
#        tensorParallelSize: 2
      enableTool: true
      toolCallParser: qwen3_coder

      nodeSelectorTerms:
      - matchExpressions:
        - key: nvidia.com/gpu.product
          operator: In
          values:
#          - NVIDIA-A100-PCIE-40GB-MIG-3g.20gb
          - NVIDIA-A100-PCIE-40GB-MIG-7g.40gb
#          - NVIDIA-A100-PCIE-40GB-MIG-1g.5gb
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - kubeworker27

#      keda:
#        enabled: false
#      lmcacheConfig:
#        enabled: false

#      hf_token: ""
#    vllmApiKey: <OMIT>
    containerSecurityContext:
      runAsNonRoot: true
    env:
      - name: USER
        value: skhuvis
      - name: LOGNAME
        value: skhuvis
      - name: VLLM_CACHE_ROOT
        value: /data/vllm_cache
      - name: FLASHINFER_WORKSPACE_BASE
        value: /data/flashinfer
      - name: TRITON_CACHE_DIR
        value: /data/triton
      - name: VLLM_NO_USAGE_STATS
        value: '1'
      - name: DO_NOT_TRACK
        value: '1'
      - name: OMP_NUM_THREADS
        value: '2'
#      - name: NVIDIA_VISIBLE_DEVICES
#        value: all
#      - name: CUDA_VISIBLE_DEVICES
#        value: '0,1'
#      - name: NCCL_DEBUG
#        value: WARN

  routerSpec:
    repository: docker-registry.osc.edu/kubernetes/lmcache/lmstack-router
    tag: v0.1.11
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
    - name: osc-registry
    env:
    - name: USER
      value: osc-chat
    - name: LOGNAME
      value: osc-chat
    servicePort: 80
    labels:
      environment: ~
      release: osc-chat
      osc.edu/service-account: osc-chat
    serviceAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics
      prometheus.io/port: '80'
    resources:
      requests:
        memory: 1500Mi
      limits:
        memory: 2000Mi
    ingress:
      enabled: true
      className: nginx
#      annotations:
#        nginx.ingress.kubernetes.io/whitelist-source-range: '131.187.45.7'
      hosts:
        - host: skhuvis-vllm.k8.osc.edu
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: osc-chat-vllm
          hosts:
            - skhuvis-vllm.k8.osc.edu
