apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryosparc.name" . }}-config
  labels: 
    {{- include "cryosparc.labels" . | nindent 4 }}
data:
  # Instance Configuration
  CRYOSPARC_DB_PATH: "/opt/cryosparc_master/database"
  CRYOSPARC_BASE_PORT: {{ .Values.global.basePort | quote }}
  CRYOSPARC_DB_CONNECTION_TIMEOUT_MS: "20000"
  # Security
  CRYOSPARC_INSECURE: "false"
  CRYOSPARC_DB_ENABLE_AUTH: "true"
  # Cluster Integration
  CRYOSPARC_CLUSTER_JOB_MONITOR_INTERVAL: "10"
  CRYOSPARC_CLUSTER_JOB_MONITOR_MAX_RETRIES: "1000000"
  # Project Configuration
  CRYOSPARC_PROJECT_DIR_PREFIX: "CS-"
  # Development
  CRYOSPARC_DEVELOP: "false"
  # Other
  CRYOSPARC_CLICK_WRAP: "true"
  # Required if the owner of the script is different from the caller
  CRYOSPARC_FORCE_USER: "true"
  # Skip the hostname check
  CRYOSPARC_FORCE_HOSTNAME: "true"

  ascend_cluster_info.json: |
    {
        "name": "ascend",
        "worker_bin_path": "{{ tpl .Values.worker_bin_path.ascend . }}",
        "send_cmd_tpl": "{{`{{ command }}`}}",
        "qsub_cmd_tpl": "sbatch -M ascend {{`{{ script_path_abs }}`}}",
        "qstat_cmd_tpl": "squeue -M ascend -j {{`{{ cluster_job_id }}`}}",
        "qdel_cmd_tpl": "scancel -M ascend {{`{{ cluster_job_id }}`}}",
        "qinfo_cmd_tpl": "sinfo -M ascend",
        "cache_path": "/tmp"
    }

  ascend_cluster_script.sh: |
    #!/bin/bash
    #SBATCH --cluster=ascend
    #SBATCH --account={{`{{ account|default({{ .Values.global.project }}) }}`}}
    #SBATCH --job-name=cryosparc_{{`{{ project_uid }}`}}_{{`{{ job_uid }}`}}
    #SBATCH --chdir={{`{{ project_dir_abs }}`}}
    #SBATCH --time={{`{{ (time|default(60)) }}`}}
    #SBATCH --output={{`{{ job_dir_abs }}`}}/output.txt
    #SBATCH --error={{`{{ job_dir_abs }}`}}/error.txt
    #SBATCH --export=ALL,LD_PRELOAD=
    #SBATCH --nodes=1
    #SBATCH --cpus-per-task={{`{{ num_cpu }}`}}
    #SBATCH --ntasks-per-node={{`{{ (ntasks_per_node|default(1)) }}`}}
    {%- if mem_gb %}
    #SBATCH --mem={{`{{ mem_gb|int }}`}}gb
    {%- endif %}
    {%- if num_gpu > 0 %}
    #SBATCH --gpus-per-node={{`{{ num_gpu }}`}}
    {%- endif %}
    export CRYOSPARC_SSD_PATH="$TMPDIR"
    {{`{{ run_cmd }}`}}

  cardinal_cluster_info.json: |
    {
        "name": "cardinal",
        "worker_bin_path": "{{ tpl .Values.worker_bin_path.cardinal . }}",
        "send_cmd_tpl": "{{`{{ command }}`}}",
        "qsub_cmd_tpl": "sbatch -M cardinal {{`{{ script_path_abs }}`}}",
        "qstat_cmd_tpl": "squeue -M cardinal -j {{`{{ cluster_job_id }}`}}",
        "qdel_cmd_tpl": "scancel -M cardinal {{`{{ cluster_job_id }}`}}",
        "qinfo_cmd_tpl": "sinfo -M cardinal",
        "cache_path": "/tmp"
    }

  cardinal_cluster_script.sh: |
    #!/bin/bash
    #SBATCH --cluster=cardinal
    #SBATCH --account={{`{{ account|default({{ .Values.global.project }}) }}`}}
    #SBATCH --job-name=cryosparc_{{`{{ project_uid }}`}}_{{`{{ job_uid }}`}}
    #SBATCH --chdir={{`{{ project_dir_abs }}`}}
    #SBATCH --time={{`{{ (time|default(60)) }}`}}
    #SBATCH --output={{`{{ job_dir_abs }}`}}/output.txt
    #SBATCH --error={{`{{ job_dir_abs }}`}}/error.txt
    #SBATCH --export=ALL,LD_PRELOAD=
    #SBATCH --nodes=1
    #SBATCH --cpus-per-task={{`{{ num_cpu }}`}}
    #SBATCH --ntasks-per-node={{`{{ (ntasks_per_node|default(1)) }}`}}
    {%- if mem_gb %}
    #SBATCH --mem={{`{{ mem_gb|int }}`}}gb
    {%- endif %}
    {%- if num_gpu > 0 %}
    #SBATCH --gpus-per-node={{`{{ num_gpu }}`}}
    {%- endif %}
    export CRYOSPARC_SSD_PATH="$TMPDIR"
    {{`{{ run_cmd }}`}}

  pitzer_cluster_info.json: |
    {
        "name": "pitzer",
        "worker_bin_path": "{{ tpl .Values.worker_bin_path.pitzer . }}",
        "send_cmd_tpl": "{{`{{ command }}`}}",
        "qsub_cmd_tpl": "sbatch -M pitzer {{`{{ script_path_abs }}`}}",
        "qstat_cmd_tpl": "squeue -M pitzer -j {{`{{ cluster_job_id }}`}}",
        "qdel_cmd_tpl": "scancel -M pitzer {{`{{ cluster_job_id }}`}}",
        "qinfo_cmd_tpl": "sinfo -M pitzer",
        "cache_path": "/tmp"
    }

  pitzer_cluster_script.sh: |
    #!/bin/bash
    #SBATCH --cluster=pitzer
    #SBATCH --account={{`{{ account|default({{ .Values.global.project }}) }}`}}
    #SBATCH --job-name=cryosparc_{{`{{ project_uid }}`}}_{{`{{ job_uid }}`}}
    #SBATCH --chdir={{`{{ project_dir_abs }}`}}
    #SBATCH --time={{`{{ (time|default(60)) }}`}}
    #SBATCH --output={{`{{ job_dir_abs }}`}}/output.txt
    #SBATCH --error={{`{{ job_dir_abs }}`}}/error.txt
    #SBATCH --export=ALL,LD_PRELOAD=
    #SBATCH --nodes=1
    #SBATCH --cpus-per-task={{`{{ num_cpu }}`}}
    #SBATCH --ntasks-per-node={{`{{ (ntasks_per_node|default(1)) }}`}}
    {%- if mem_gb %}
    #SBATCH --mem={{`{{ mem_gb|int }}`}}gb
    {%- endif %}
    {%- if num_gpu > 0 %}
    #SBATCH --gpus-per-node={{`{{ num_gpu }}`}}
    {%- endif %}
    export CRYOSPARC_SSD_PATH="$TMPDIR"
    {{`{{ run_cmd }}`}}
