apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ required "License must be provided" .Values.license | b64enc }}
  email: {{ required "Admin information must be provided" .Values.admin.email | b64enc | quote }}
  username: {{ required "Admin information must be provided" .Values.admin.username | b64enc | quote }}
  password: {{ required "Admin information must be provided" .Values.admin.password | b64enc | quote }}
