---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
  {{- if (include "cryosparc.alert.receiver" .) }}
    receiver: {{ include "cryosparc.alert.receiver" . }}
  {{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.global.basePort }}
  selector:
    {{- include "cryosparc.selectorLabels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparc.name" . }}-nodeport
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
  {{- if (include "cryosparc.alert.receiver" .) }}
    receiver: {{ include "cryosparc.alert.receiver" . }}
  {{- end }}
spec:
  selector:
    {{- include "cryosparc.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Local
  ports:
  - name: webapp
    protocol: TCP
    port: {{ .Values.global.basePort }}
    targetPort: {{ .Values.global.basePort }}
    nodePort: {{ .Values.global.basePort }}
  - name: mongod
    protocol: TCP
    port: {{ add .Values.global.basePort 1 }}
    targetPort: {{ add .Values.global.basePort 1 }}
    nodePort: {{ add .Values.global.basePort 1 }}
  - name: cmd-server
    protocol: TCP
    port: {{ add .Values.global.basePort 2 }}
    targetPort: {{ add .Values.global.basePort 2 }}
    nodePort: {{ add .Values.global.basePort 2 }}
  - name: cmd-vis
    protocol: TCP
    port: {{ add .Values.global.basePort 3 }}
    targetPort: {{ add .Values.global.basePort 3 }}
    nodePort: {{ add .Values.global.basePort 3 }}
  {{- if (include "cryosparc.isV5" .) }}
  - name: redis
    protocol: TCP
    port: {{ add .Values.global.basePort 4 }}
    targetPort: {{ add .Values.global.basePort 4 }}
    nodePort: {{ add .Values.global.basePort 4 }}
  {{- end }}
  - name: rtp-server
    protocol: TCP
    port: {{ add .Values.global.basePort 5 }}
    targetPort: {{ add .Values.global.basePort 5 }}
    nodePort: {{ add .Values.global.basePort 5 }}
  - name: webapp-api
    protocol: TCP
    port: {{ add .Values.global.basePort 6 }}
    targetPort: {{ add .Values.global.basePort 6 }}
    nodePort: {{ add .Values.global.basePort 6 }}
  {{- if (include "cryosparc.isV5" .) }}
  # Commet out until used to avoid Prometheus alerts untl using Prometheus operator
  # - name: reserved-1
  #   protocol: TCP
  #   port: {{ add .Values.global.basePort 7 }}
  #   targetPort: {{ add .Values.global.basePort 7 }}
  #   nodePort: {{ add .Values.global.basePort 7 }}
  # - name: reserved-2
  #   protocol: TCP
  #   port: {{ add .Values.global.basePort 8 }}
  #   targetPort: {{ add .Values.global.basePort 8 }}
  #   nodePort: {{ add .Values.global.basePort 8 }}
  # - name: reserved-3
  #   protocol: TCP
  #   port: {{ add .Values.global.basePort 9 }}
  #   targetPort: {{ add .Values.global.basePort 9 }}
  #   nodePort: {{ add .Values.global.basePort 9 }}
  {{- end }}
  type: NodePort
