apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{ tpl (include "osc.common.serviceAccount" .) . }}
    {{- include "cryosparc.labels" . | nindent 4 }}
  {{- if (include "cryosparc.alert.receiver" .) }}
    receiver: {{ include "cryosparc.alert.receiver" . }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cryosparc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ tpl (include "osc.common.serviceAccount" .) . }}
        {{- include "cryosparc.selectorLabels" . | nindent 8 }}
      {{- if (include "cryosparc.alert.receiver" .) }}
        receiver: {{ include "cryosparc.alert.receiver" . }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cryosparc.name" . }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: false
      hostIPC: false
      hostPID: false
      {{- $nodes := include "cryosparc.nodes" . | fromJsonArray }}
      {{- if $nodes }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        {{- $nodes | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "cryosparc.name" . }}
        image: {{ tpl .Values.image.repository . }}:{{ include "cryosparc.imageTag" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "cryosparc.name" . }}-envs
        command: ["sh", "-c"]
        args:
        - |
          mkdir -p /cryosparc_data/lanes;
          mkdir -p /cryosparc_data/database;
          mkdir -p /cryosparc_data/run;
          printenv MY_NODE_NAME;
          export CRYOSPARC_MASTER_HOSTNAME="${MY_NODE_NAME}";
          cryosparcm start;
          cryosparcm status;
          echo "Creating an admin user";
          cryosparcm cli "create_user('initial', '$ADMIN_EMAIL', '$ADMIN_PASSWORD', 'SciApps', 'Admin', True)";
          unset ADMIN_EMAIL ADMIN_PASSWORD
          echo "Updating cluster lanes";
          ls -d -1 /opt/cryosparc_master/lanes/* |while read x; do
            cd $x;
            cryosparcm cluster connect;
          done;
          echo "Keep CryoSPARC running";
          while true; do 
            sleep 3600;
          done;
        lifecycle:
          preStop:
            exec:
              command: ['cryosparcm', 'stop']   # Fix rollout restart issue
        workingDir: /opt/cryosparc_master
        env:
        - name: SLURM_CONF
          value: {{ .Values.slurmConf }}
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CRYOSPARC_LICENSE_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "cryosparc.name" . }}
              key: license
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ include "cryosparc.name" . }}
              key: email
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "cryosparc.name" . }}
              key: password
        volumeMounts:
        - name: {{ include "cryosparc.name" . }}-data
          mountPath: /cryosparc_data
        - name: project
          mountPath: {{ tpl .Values.mounts.project . }}
        - name: home
          mountPath: {{ tpl .Values.mounts.home . }}
        - name: munge-socket
          mountPath: /var/run/munge/munge.socket.2
        - name: slurm-conf
          mountPath: /etc/slurm
        - name: sssd-pipes
          mountPath: /var/lib/sss/pipes
        - name: sssd-conf
          mountPath: /etc/sssd
        - name: ascend-cluster-conf
          mountPath: /cryosparc_data/lanes/ascend
        - name: pitzer-cluster-conf
          mountPath: /cryosparc_data/lanes/pitzer
        - name: cardinal-cluster-conf
          mountPath: /cryosparc_data/lanes/cardinal
        resources: {{ toYaml (index .Values.global.env (include "osc.common.environment" .) "podResources") | nindent 10 }}
        ports:
          - containerPort: {{ .Values.global.basePort }}
            name: http
          - containerPort: {{ add .Values.global.basePort 1 }}
            name: mongod
          - containerPort: {{ add .Values.global.basePort 2 }}
            name: cmd-server
          - containerPort: {{ add .Values.global.basePort 5 }}
            name: rtp-server
      nodeSelector: 
        {{ include "osc.common.nodeSelectorRole" . }}
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: cryosparc-home
        hostPath:
          path: {{ tpl .Values.mounts.home . }}
          type: Directory
      - name: project
        hostPath:
          path: {{ tpl .Values.mounts.project . }}
          type: Directory
      - name: munge-socket
        hostPath:
          path: /var/run/munge/munge.socket.2
          type: Socket
      - name: slurm-conf
        hostPath:
          path: /etc/slurm
          type: Directory
      - name: sssd-pipes
        hostPath:
          path: /var/lib/sss/pipes
          type: Directory
      - name: sssd-conf
        hostPath:
          path: /etc/sssd
          type: Directory
      - name: ascend-cluster-conf
        configMap:
          name: {{ include "cryosparc.name" . }}-lanes
          items:
          - key: "ascend_cluster_info.json"
            path: "cluster_info.json"
          - key: "ascend_cluster_script.sh"
            path: "cluster_script.sh"
      - name: pitzer-cluster-conf
        configMap:
          name: {{ include "cryosparc.name" . }}-lanes
          items:
          - key: "pitzer_cluster_info.json"
            path: "cluster_info.json"
          - key: "pitzer_cluster_script.sh"
            path: "cluster_script.sh"
      - name: cardinal-cluster-conf
        configMap:
          name: {{ include "cryosparc.name" . }}-lanes
          items:
          - key: "cardinal_cluster_info.json"
            path: "cluster_info.json"
          - key: "cardinal_cluster_script.sh"
            path: "cluster_script.sh"
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
  - metadata:
      name: {{ include "cryosparc.name" . }}-data
      annotations:
        osc.edu/fileset: '{{ .Values.global.project }}'
    spec:
      storageClassName: {{ .Values.storage.projectStorageClass }}
      accessModes:
      - {{ .Values.storage.accessModes }}
      resources:
        requests:
          storage: 500Gi
