global:
  environment: dev
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
webservice:
  ingress:
    host: test.local
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5
