apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: legacy-service-endpoints
  namespace: {{ .Release.Namespace }}
  labels:
    discovery: annotations
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  jobName: service-endpoints
  kubernetesSDConfigs:
    - role: Service
  relabelings:
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: 'true'
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_match_metrics, __meta_kubernetes_service_port_name]
      action: drop
      regex: 'true;.*[^metrics].*'
    # A way to find legacy scrapes
    - targetLabel: 'discovery'
      replacement: 'annotations'
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      targetLabel: __metrics_path__
      regex: '(.+)'
    - sourceLabels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      targetLabel: __address__
      regex: '([^:]+)(?::\d+)?;(\d+)'
      replacement: '$1:$2'
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: kubernetes_name
    - sourceLabels: [kubernetes_name, __meta_kubernetes_service_port_name]
      regex: '(.+);(.+)'
      replacement: '$1:$2'
      targetLabel: instance
    - sourceLabels: [kubernetes_name, __meta_kubernetes_service_port_name, __address__]
      regex: '(.+);;([^:]+):(\d+)?'
      replacement: '$1:$3'
      targetLabel: instance
    - sourceLabels: [instance]
      targetLabel: host
    - regex: "app_kubernetes_io_(managed_by|version)"
      action: labeldrop
    - regex: "helm_sh_chart"
      action: labeldrop
