apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nodes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  jobName: nodes
  kubernetesSDConfigs:
    - role: Node
  scheme: https
  metricsPath: /metrics
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  authorization:
    type: Bearer
    credentialsFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - sourceLabels: [__meta_kubernetes_node_name]
      regex: '(.+)'
      replacement: '$1'
      targetLabel: host
    - sourceLabels: [host]
      targetLabel: node
    - regex: "cpu_(feature|model)_.+"
      action: labeldrop
    - regex: "host_model_.+"
      action: labeldrop
    - regex: "(feature|hyperv|scheduling)_node_.+"
      action: labeldrop
    - regex: "machine_type_.+"
      action: labeldrop
    - regex: "kubevirt_io_.+"
      action: labeldrop
    - regex: "nvidia_com_.+"
      action: labeldrop
    - regex: "cluster"
      action: labeldrop
