
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osc-chat.fullname" . }}-app-config
  labels:
    {{- include "osc-chat.labels" . | nindent 4 }}
data:
  # Application configuration
  ENVIRONMENT: {{ .Values.environment | quote }}
  
  # Service URLs
  #POSTGRES_HOST: {{ include "osc-chat.postgresql.host" . | quote }}
  POSTGRES_PORT: {{ include "osc-chat.postgresql.port" . | quote }}
  POSTGRES_DB: {{ include "osc-chat.postgresql.database" . | quote }}
  POSTGRES_USER: {{ include "osc-chat.postgresql.username" . | quote }}

  # ai-ta-backend expected PostgreSQL envs (aliases)
  POSTGRES_ENDPOINT: {{ include "osc-chat.postgresql.host" . | quote }}
  POSTGRES_DATABASE: {{ include "osc-chat.postgresql.database" . | quote }}
  POSTGRES_USERNAME: {{ include "osc-chat.postgresql.username" . | quote }}
  
  REDIS_HOST: {{ include "osc-chat.redis.host" . | quote }}
  REDIS_PORT: {{ include "osc-chat.redis.port" . | quote }}
  
  RABBITMQ_HOST: {{ include "osc-chat.rabbitmq.host" . | quote }}
  RABBITMQ_PORT: {{ include "osc-chat.rabbitmq.port" . | quote }}
  RABBITMQ_QUEUE: {{ include "osc-chat.fullname" . }}
  
  QDRANT_URL: "http://{{ include "osc-chat.fullname" . }}-qdrant:6333"
  MINIO_URL: "http://{{ include "osc-chat.fullname" . }}-minio:9000"
  MINIO_PUBLIC_URL: {{ printf "https://%s" (.Values.minio.ingress.hostname)  | quote }}
  KEYCLOAK_URL: {{ .Values.keycloak.url | quote }}
  
  # Application specific
  QDRANT_COLLECTION_NAME: {{ include "osc-chat.fullname" . | quote }}
  S3_BUCKET_NAME: {{ .Values.worker.env.S3_BUCKET_NAME | quote }}
