
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osc-chat.fullname" . }}-app-config
  labels:
    {{- include "osc-chat.labels" . | nindent 4 }}
data:
  {{- include "osc-chat.app.config" . | nindent 2 }}
