{{- if .Values.frontend.ingress.enabled -}}
{{- $fullName := include "osc-chat.fullname" . -}}
{{- $frontendPort := .Values.frontend.service.port -}}
{{- $backendPort := .Values.backend.service.port -}}
{{- if and .Values.frontend.ingress.className (not (hasKey .Values.frontend.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.frontend.ingress.annotations "kubernetes.io/ingress.class" .Values.frontend.ingress.className}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend
  labels:
    {{- include "osc-chat.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          # Frontend root
          - path: /
            {{- if (index .paths 0).pathType }}
            pathType: {{ (index .paths 0).pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}-frontend
                port:
                  number: {{ $frontendPort }}
          # Backend API under /api
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-backend
                port:
                  number: {{ $backendPort }}
          {{- if $.Values.minio.enable }}
          # MinIO console under /minio
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-minio
                port:
                  number: 9000
          {{- end }}
          {{- if $.Values.ollama.enabled }}
          # Ollama API under /ollama
          - path: {{ default "/ollama" $.Values.paths.ollama }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-ollama
                port:
                  number: {{ $.Values.ollama.service.port }}
          {{- end }}
    {{- end }}
{{- end }}


