{{- if .Values.qdrant.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osc-chat.fullname" . }}-qdrant-setup
  labels:
    {{- include "osc-chat.labels" . | nindent 4 }}
    receiver: '{{ index .Values.global.alert.receiver }}'
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"  # Run before other services
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "osc-chat.labels" . | nindent 8 }}
        app.kubernetes.io/component: qdrant
        app.kubernetes.io/name: qdrant
        receiver: '{{ index .Values.global.alert.receiver }}'
    spec:
      imagePullSecrets:
        - name: {{ include "osc.common.imagePullSecret.name" . }}
      restartPolicy: OnFailure
      containers:
      - name: qdrant-setup
        image: {{ .Values.global.imageRegistry }}/kubernetes/portainer/kubectl-shell:2.39.0
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
        command:
          - /bin/sh
          - -c
          - |
            curl --header "api-key: ${QDRANT_API_KEY}" -sf "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" || \
            curl --header "api-key: ${QDRANT_API_KEY}" -X PUT "${QDRANT_URL}/collections/${QDRANT_COLLECTION_NAME}" \
            -H "Content-Type: application/json" \
            -d '{
              "vectors": {
                "size": {{ .Values.global.embedding.vectorLen }},
                "distance": "Cosine"
              }
            }'
        env:
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "osc-chat.fullname" . }}-app-config
              key: QDRANT_URL
        - name: QDRANT_COLLECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "osc-chat.fullname" . }}-app-config
              key: QDRANT_COLLECTION_NAME
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "osc-chat.fullname" . }}-qdrant-apikey
              key: api-key
{{ end }}
