{{- if .Values.frontend.enabled }}
{{- if .Values.database.redis.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "osc-chat.fullname" . }}-allow-frontend-to-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "osc-chat.frontend.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
{{- end }}
{{- if .Values.backend.enabled }}
{{- if .Values.database.redis.enable }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "osc-chat.fullname" . }}-allow-backend-to-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "osc-chat.backend.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
{{- end }}
