---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osc-chat.fullname" . }}-app-secrets
  labels:
    {{- include "osc-chat.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "osc-chat.app.secrets" . | nindent 2 }}

