apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret.name }}
  labels:
    {{- include "osc.common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "osc.common.imagePullSecret" . }}
