{{- range $name, $vm := .Values.vms }}
{{- if and (eq $vm.os "windows11") (not (eq $vm.deployed true)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-finalize" $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kubevirt-vm.labels" $ | nindent 4 }}
    {{- include "kubevirt-vm.vm.labels" (dict "root" $ "name" $name "vm" $vm) | nindent 4 }}

stringData:
  autounattend.xml: |-
    <?xml version="1.0" encoding="utf-8"?>
    <!-- responsible for installing windows, ignored on sysprepped images -->
  finalize.ps1: |-
    Start-Transcript -Path "C:\Windows\Logs\Scripts\finalize.log" -Append

    Write-Host "Set Administrator password"
    net user Administrator {{ $vm.adminPassword | default $.Values.windows11.defaults.adminPassword }}

    Write-Host "Disable auto login"
    Set-ItemProperty -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "AutoAdminLogon" -Value 0

  {{- $joinDomain := $.Values.windows11.defaults.joinDomain }}
  {{- if hasKey $vm "joinDomain" }}
  {{- $joinDomain = $vm.joinDomain }}
  {{- end }}
  {{- if eq $joinDomain true }}
    Write-Host "Join domain"
    $password = ConvertTo-SecureString "{{ $.Values.windows11.defaults.domainAdminPassword }}" -AsPlainText -Force
    $cred = New-Object System.Management.Automation.PSCredential ("{{ $.Values.windows11.defaults.domainAdminUser }}", $password)
    Add-Computer -DomainName "{{ $.Values.windows11.defaults.msadDomain }}" -ComputerName "{{ $vm.hostname | default $name }}" -Credential $cred -Force
  {{- end }}

    Write-Host "Shutdown"
    Stop-Computer -Force
{{- end }}
{{- end }}
