apiVersion: v1
kind: Namespace
metadata:
  name: k8-ldap-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-uid-map
  namespace: k8-ldap-configmap
data:
  user-immunegenetics: "41773"
  user-k8spublic: "38635"
  user-focalmapdev: "36971"
  user-nominatim: "39237"
  user-phylogatrdev: "33253"
  user-test: "1000"
  user-webmo: "42113"
  user-emthub: "42168"
  user-harvesttest: "44687"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-gid-map
  namespace: k8-ldap-configmap
data:
  user-immunegenetics: "4215"
  user-k8spublic: "4097"
  user-focalmapdev: "2925"
  user-nominatim: "4097"
  user-phylogatrdev: "6314"
  user-test: "1001"
  user-webmo: "3608"
  user-emthub: "8052"
  user-harvesttest: "8377"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-gids-map
  namespace: k8-ldap-configmap
data:
  user-immunegenetics: '["4215"]'
  user-k8spublic: '["4097"]'
  user-focalmapdev: '["2925","6393","7175"]'
  user-nominatim: '["4097"]'
  user-phylogatrdev: '["6314","6557","6558"]'
  user-test: '["1001","1002"]'
  user-webmo: '["3608","3427"]'
  user-emthub: '["8052"]'
  user-harvesttest: '["8377","8388","65533"]'
