apiVersion: v1
kind: Namespace
metadata:
  name: k8-ldap-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-uid-map
  namespace: k8-ldap-configmap
data:
  user-phylogatrdev: "33253"
  user-test: "1000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-gid-map
  namespace: k8-ldap-configmap
data:
  user-phylogatrdev: "6314"
  user-test: "1001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-gids-map
  namespace: k8-ldap-configmap
data:
  user-phylogatrdev: '["6314","6557","6558"]'
  user-test: '["1001","1002"]'
