# REF: https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/ci/h2-values.yaml
extraEnv: |
  - name: DB_VENDOR
    value: h2
  - name: KEYCLOAK_USER_FILE
    value: /secrets/admin-creds/user
  - name: KEYCLOAK_PASSWORD_FILE
    value: /secrets/admin-creds/password
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true
secrets:
  admin-creds:
    stringData:
      user: admin
      password: secret

extraVolumeMounts: |
  - name: admin-creds
    mountPath: /secrets/admin-creds
    readOnly: true
extraVolumes: |
  - name: admin-creds
    secret:
      secretName: keycloak-admin-creds
postgresql:
  enabled: false