image:
  repository: bitnamilegacy/keycloak
postgresql:
  image:
    repository: bitnamilegacy/postgresql
resources:
  limits:
    cpu: 1
    memory: 3072Mi
  requests:
    cpu: 250m
    memory: 2048Mi
auth:
  adminUser: admin
  adminPassword: secret
