---
manager:
  config:
    keycloakURL: http://keycloak.keycloak.svc.cluster.local
    adminUsername: admin
    adminPassword: secret
    adminRealm: master
    defaultRealm: master
    allowedRealms:
      - master
    clientIdPrefix: kubernetes
networkPolicy:
  allowMetricsFromPods: true
