# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /fs
    containerPath: /fs
  - hostPath: /users
    containerPath: /users
  - hostPath: /etc/slurm
    containerPath: /etc/slurm
  - hostPath: /var/run/munge
    containerPath: /var/run/munge
  - hostPath: /var/lib/sss/pipes
    containerPath: /var/lib/sss/pipes
  - hostPath: /etc/sssd
    containerPath: /etc/sssd
- role: worker
  extraMounts:
  - hostPath: /fs
    containerPath: /fs
  - hostPath: /users
    containerPath: /users
  - hostPath: /etc/slurm
    containerPath: /etc/slurm
  - hostPath: /var/run/munge
    containerPath: /var/run/munge
  - hostPath: /var/lib/sss/pipes
    containerPath: /var/lib/sss/pipes
  - hostPath: /etc/sssd
    containerPath: /etc/sssd
