imagePullSecrets:
  osc-registry:
    registry: docker-registry.osc.edu
    username: robot$webservices-read
    password: IMAGE-PULL-PASSWORD
admissionController:
  replicaCount: 1
  createSelfSignedCert: true
  container:
    extraArgs:
      loggingFormat: text
      exceptionNamespace: kyverno
      webhookTimeout: 30
config:
  # TODO: Remove once fixed: https://github.com/kyverno/kyverno/issues/3190
  resourceFilters:
  - "[ConfigMap,*,*]"
  - "[*,local-path-storage,*]"
  - "[Event,*,*]"
  - "[*,default,*]"
  - "[*,kube-system,*]"
  - "[*,kube-public,*]"
  - "[*,kube-node-lease,*]"
  - "[Node,*,*]"
  - "[APIService,*,*]"
  - "[TokenReview,*,*]"
  - "[SubjectAccessReview,*,*]"
  - "[SelfSubjectAccessReview,*,*]"
  - "[*,kyverno,*]"
  - "[Binding,*,*]"
  - "[ReplicaSet,*,*]"
  - "[ReportChangeRequest,*,*]"
  - "[ClusterReportChangeRequest,*,*]"
  - "[*,keycloak,*]"
  webhooks:
    namespaceSelector:
      matchExpressions:
        - key: osc.edu/role
          operator: In
          values:
            - webservice
            - paas
