imagePullSecrets:
  osc-registry:
    registry: docker-registry.osc.edu
    username: robot$webservices-read
    password: IMAGE-PULL-PASSWORD
admissionController:
  replicaCount: 1
  createSelfSignedCert: true
  container:
    extraArgs:
      loggingFormat: text
      exceptionNamespace: kyverno
      webhookTimeout: 30
config:
  resourceFiltersIncludeNamespaces:
  - local-path-storage
  - default
  - kyverno
  - keycloak
  webhooks:
    namespaceSelector:
      matchExpressions:
        - key: osc.edu/role
          operator: In
          values:
            - webservice
            - paas
