global:
  environment: ""
  imageTag: v0.1.0
  oscServiceAccount: k8spublic
  env:
    production:
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    test:
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    dev:
      replicas: 1
      image:
        tag: latest
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      maintenance:
        groups:
          - wiagstf
webservice:
  appType: none
  auth:
    enable: false
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/chatsqc
  env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: 'false'
  startupProbe:
    httpGet:
      path: /healthz
  livenessProbe:
    httpGet:
      path: /healthz
  readinessProbe:
    httpGet:
      path: /healthz
  service:
    port: 8080
  alert:
    receiver: gateways
  debugGroups:
    - wiagstf
