# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  oscServiceAccount: prometheus
  nodeSelectorRole: infrastructure
  imagePullSecret:
    name: osc-registry
    registry: docker-registry.osc.edu
    username: robot$osc-read
    password:
  networkPolicy:
    create: false
  webservicesDeploy:
    create: false
  auth:
    enable: true
    upstream: http://prometheus-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
  ingress:
    # -- Ingress host value
    host: ""
    # -- Ingress host alias
    hostAlias: ""
  storageClass: nfs-infra

nameOverride: ""
fullnameOverride: ""

kube-prometheus-stack:
  fullnameOverride: prometheus
  crds:
    enabled: false
    upgradeJob:
      enabled: false
  defaultRules:
    # TODO: Evaluate which we may want
    create: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeApiServer:
    serviceMonitor:
      relabelings:
      - sourceLabels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
  kubelet:
    enabled: false
  coreDns:
    service:
      enabled: false
    serviceMonitor:
      selector:
        matchLabels:
          k8s-app: kube-dns
      port: metrics
  # TODO: Evaluate how to get etcd monitoring into the operator
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  # TODO: Adopt the stack's kube-state-metrics
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheusOperator:
    fullnameOverride: prometheus-operator
    admissionWebhooks:
      deployment:
        enabled: true
        nodeSelector:
          node-role.kubernetes.io/infrastructure: ''
      patch:
        nodeSelector:
          node-role.kubernetes.io/infrastructure: ''
      certManager:
        enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 256Mi
    nodeSelector:
      node-role.kubernetes.io/infrastructure: ''
    prometheusConfigReloader:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    kubeletService:
      enabled: false
    kubeletEndpointsEnabled: false
    kubeletEndpointSliceEnabled: false
  prometheus:
    service:
      port: 9090
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/component: server
    prometheusSpec:
      image:
        # TODO: Use old version if upgrade is problematic
        # tag: v2.44.0
        # Allow debugging by not using distroless
        # tag: v3.11.3-distroless
        tag: v3.11.3
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
      scrapeInterval: 1m
      scrapeTimeout: 10s
      scrapeClasses:
        - name: kubernetes
          default: false
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          authorization:
            type: Bearer
            credentialsFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      evaluationInterval: 1m
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: '{{ .Values.global.storageClass }}'
            accessModes: ["ReadWriteMany"]
            resources:
              requests:
                storage: 100Gi
      resources:
        limits:
          cpu: 4
          memory: 16Gi
        requests:
          cpu: 2
          memory: 8Gi
      nodeSelector:
        node-role.kubernetes.io/infrastructure: ''
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector:
        matchExpressions:
          - key: osc.edu/role
            operator: NotIn
            values: ["paas"]
      podMonitorNamespaceSelector:
        matchExpressions:
          - key: osc.edu/role
            operator: NotIn
            values: ["paas"]
      securityContext:
        runAsGroup: 94
        runAsUser: 94
        fsGroup: 94
      externalLabels:
        cluster: kubernetes
        environment: '{{ include "osc.common.environment" . }}'

prometheus-pushgateway:
  fullnameOverride: pushgateway
  extraArgs:
    - --persistence.file=/data/pushgateway.data
    - --persistence.interval=5m
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  nodeSelector:
    node-role.kubernetes.io/infrastructure: ''
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    runAsNonRoot: true
  serviceMonitor:
    enabled: true
    namespace: ~
    interval: 15s
    scrapeTimeout: 10s
  persistentVolume:
    enabled: false
  networkPolicy:
    customSelectors:
      - podSelector: {}
      - namespaceSelector:
          matchLabels:
            osc.edu/access-dynamo-platform: "true"
  extraContainers:
    - name: cleaner
      image: ghcr.io/abatilo/pushgateway-cleaner:v0.1.3
      imagePullPolicy: IfNotPresent
      args:
        - '-pushgateway-url'
        - 'http://localhost:9091'
        - '-sync-period'
        - '2m'
        - '-ttl'
        - '5m'
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
        privileged: false
        runAsNonRoot: true
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 128Mi
watch:
  image:
    repository: docker-registry.osc.edu/kubernetes/weaveworks/watch
    tag: master-0c44bf6
    pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 94
    runAsGroup: 94
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 50Mi

blackboxExporter:
  name: blackbox-exporter
  configName: blackbox-exporter-config
  image:
    repository: quay.io/prometheus/blackbox-exporter
    pullPolicy: IfNotPresent
    tag: "v0.24.0"
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      # Need the following if enable ICMP module
      # add:
      # - NET_RAW
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 50Mi
  service:
    type: ClusterIP
    port: 9115
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics

sslExporter:
  name: ssl-exporter
  configName: ssl-exporter-config
  rbac:
    create: false
  image:
    repository: docker-registry.osc.edu/kubernetes/ribbybibby/ssl-exporter
    pullPolicy: IfNotPresent
    tag: "2.4.2"
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 50Mi
  service:
    type: ClusterIP
    port: 9219
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics

ingressName: ingress-nginx
namespaceReaper: k8-namespace-reaper
kedaNamespace: keda
headlampNamespace: headlamp

kube-state-metrics:
  nameOverride: kube-state-metrics
  fullnameOverride: kube-state-metrics
  prometheusScrape: false
  service:
    annotations:
      prometheus.io/probe_skip: "true"
  collectors: []
  selfMonitor:
    enabled: true
    telemetryPort: 8081
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    runAsNonRoot: true
  nodeSelector:
    node-role.kubernetes.io/infrastructure: ''

dcgm-exporter:
  nameOverride: dcgm-exporter
  fullnameOverride: dcgm-exporter
  image:
    repository: docker-registry.osc.edu/osc/dcgm-exporter
    tag: 4.4.1-4.6.0-ubuntu22.04
  imagePullSecrets:
    - name: osc-registry
  arguments:
    - --no-hostname
  extraEnv:
    - name: "__DCGM_DBG_LVL"
      value: "NONE"
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9400'
  service:
    enable: false
    port: 9400
  serviceMonitor:
    enabled: false
  resources:
    limits:
      cpu: '2'
      memory: '1Gi'
    requests:
      cpu: '1'
      memory: '512Mi'
  nodeSelector:
    feature.node.kubernetes.io/pci-10de.present: "true"

hook:
  image:
    repository: docker-registry.osc.edu/kubernetes/portainer/kubectl-shell
    tag: '2.39.0'
