# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  oscServiceAccount: prometheus
  nodeSelectorRole: infrastructure
  imagePullSecret:
    name: osc-registry
    registry: docker-registry.osc.edu
    username: robot$osc-read
    password:
  networkPolicy:
    create: false
  webservicesDeploy:
    create: false
  auth:
    enable: true
    upstream: http://prometheus-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
  ingress:
    # -- Ingress host value
    host: ""
    # -- Ingress host alias
    hostAlias: ""
  storageClass: nfs-infra

nameOverride: ""
fullnameOverride: ""

kube-prometheus-stack:
  fullnameOverride: prometheus
  crds:
    enabled: false
    upgradeJob:
      enabled: false
  defaultRules:
    # TODO: Evaluate which we may want
    create: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeApiServer:
    serviceMonitor:
      relabelings:
      - sourceLabels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
  kubelet:
    enabled: false
  coreDns:
    service:
      enabled: false
    serviceMonitor:
      selector:
        matchLabels:
          k8s-app: kube-dns
      port: metrics
  # TODO: Evaluate how to get etcd monitoring into the operator
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  # TODO: Adopt the stack's kube-state-metrics
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheusOperator:
    fullnameOverride: prometheus-operator
    admissionWebhooks:
      deployment:
        enabled: true
        nodeSelector:
          node-role.kubernetes.io/infrastructure: ''
      patch:
        nodeSelector:
          node-role.kubernetes.io/infrastructure: ''
      certManager:
        enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 256Mi
    nodeSelector:
      node-role.kubernetes.io/infrastructure: ''
    prometheusConfigReloader:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
  prometheus:
    service:
      port: 9090
    prometheusSpec:
      image:
        # TODO: Use old version if upgrade is problematic
        # tag: v2.44.0
        # Allow debugging by not using distroless
        # tag: v3.11.3-distroless
        tag: v3.11.3
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
      scrapeInterval: 1m
      scrapeTimeout: 10s
      evaluationInterval: 1m
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: '{{ .Values.global.storageClass }}'
            accessModes: ["ReadWriteMany"]
            resources:
              requests:
                storage: 100Gi
      resources:
        limits:
          cpu: 4
          memory: 16Gi
        requests:
          cpu: 2
          memory: 8Gi
      nodeSelector:
        node-role.kubernetes.io/infrastructure: ''
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector:
        matchExpressions:
          - key: osc.edu/role
            operator: NotIn
            values: ["paas"]
      podMonitorNamespaceSelector:
        matchExpressions:
          - key: osc.edu/role
            operator: NotIn
            values: ["paas"]
      securityContext:
        runAsGroup: 94
        runAsUser: 94
        fsGroup: 94
      externalLabels:
        cluster: kubernetes
        environment: '{{ include "osc.common.environment" . }}'
      additionalScrapeConfigs:
        # TODO: Remove kubevirt-scrape once using ServiceMonitor in Helm chart
        - job_name: kubevirt
          scheme: https
          metrics_path: /metrics
          tls_config:
            insecure_skip_verify: true
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_endpoints_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: (kubevirt|cdi);(kubevirt|cdi)-prometheus-metrics;metrics
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_endpoint_node_name]
            target_label: node
          - regex: "(app_kubernetes_io_version|prometheus_kubevirt_io|prometheus_cdi_kubevirt_io)"
            action: labeldrop
          - regex: "np_kubevirt_io_allow_access_cluster_services"
            action: labeldrop
          - regex: ".+_(hash|generation|createVersion)"
            action: labeldrop
        - job_name: services
          scheme: http
          metrics_path: "/probe"
          kubernetes_sd_configs:
          - role: service
          params:
            module:
            - tcp_connect
          relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_job]
            action: drop
            regex: "^user-.+;.+"
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe_skip]
            action: drop
            regex: 'true'
          - source_labels: [__meta_kubernetes_service_port_protocol]
            action: keep
            regex: TCP
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement: 'blackbox-exporter.{{ .Release.Namespace }}.svc.cluster.local:9115'
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe_module]
            regex: "(.+)"
            replacement: "$1"
            target_label: __param_module
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe_scheme, __param_target]
            regex: "(.+);(.+)"
            replacement: '${1}://${2}'
            target_label: __param_target
          - source_labels: [__param_target, __meta_kubernetes_service_annotation_prometheus_io_probe_path]
            regex: "(.+);(.+)"
            replacement: '${1}${2}'
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_name
          - regex: "app_kubernetes_io_(managed_by|version)"
            action: labeldrop
          - regex: "helm_sh_chart"
            action: labeldrop
        - job_name: service-endpoints
          kubernetes_sd_configs:
          - role: service
          relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: 'true'
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_match_metrics, __meta_kubernetes_service_port_name]
            action: drop
            regex: 'true;.*[^metrics].*'
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: '(.+)'
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: '$1:$2'
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_name
          - source_labels: [kubernetes_name, __meta_kubernetes_service_port_name]
            regex: '(.+);(.+)'
            replacement: '$1:$2'
            target_label: instance
          - source_labels: [kubernetes_name, __meta_kubernetes_service_port_name, __address__]
            regex: '(.+);;([^:]+):(\d+)?'
            replacement: '$1:$3'
            target_label: instance
          - source_labels: [instance]
            target_label: host
          - regex: "app_kubernetes_io_(managed_by|version)"
            action: labeldrop
          - regex: "helm_sh_chart"
            action: labeldrop
        - job_name: pod-endpoints
          metrics_path: /metrics
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: 'true'
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '(.+);(.+)'
          - source_labels: [__meta_kubernetes_pod_container_port_protocol]
            action: keep
            regex: 'TCP'
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: '(.+)'
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: '$1:$2'
          - source_labels: [__meta_kubernetes_pod_node_name]
            regex: '(.+)'
            replacement: '$1'
            target_label: host
          - source_labels: [host]
            target_label: node
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_name
          - source_labels: [kubernetes_name, __meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: '(.+);(.+)'
            replacement: '$1:$2'
            target_label: instance
        - job_name: ingress-probe
          scrape_timeout: 60s
          scrape_interval: 3m
          scheme: http
          metrics_path: /probe
          params:
            module:
              - https
          kubernetes_sd_configs:
          - role: ingress
          relabel_configs:
          - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe_skip]
            action: drop
            regex: 'true'
          - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe_scheme]
            regex: (.+)
            replacement: ${1}
            target_label: __meta_kubernetes_ingress_scheme
          - source_labels: [__meta_kubernetes_ingress_scheme, __address__, __meta_kubernetes_ingress_path]
            regex: (.+);(.+);(.+)
            replacement: ${1}://${2}${3}
            target_label: __param_target
          - source_labels: [__meta_kubernetes_ingress_scheme, __address__, __meta_kubernetes_ingress_annotation_prometheus_io_probe_path]
            regex: (.+);(.+);(.+)
            replacement: ${1}://${2}${3}
            target_label: __param_target
          - source_labels: [__meta_kubernetes_ingress_scheme]
            regex: (.+)
            replacement: ${1}
            target_label: __param_module
          - target_label: __address__
            replacement: 'blackbox-exporter.{{ .Release.Namespace }}.svc.cluster.local:9115'
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_ingress_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_ingress_name]
            target_label: kubernetes_name
          - regex: "app_kubernetes_io_(managed_by|version)"
            action: labeldrop
          - regex: "helm_sh_chart"
            action: labeldrop
        - job_name: ingress-ssl
          scrape_timeout: 60s
          scrape_interval: 3m
          scheme: http
          metrics_path: /probe
          params:
            module:
              - https
          kubernetes_sd_configs:
          - role: ingress
          relabel_configs:
          - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe_skip]
            action: drop
            regex: 'true'
          - source_labels: [__meta_kubernetes_ingress_scheme]
            action: keep
            regex: https
          - source_labels: [__meta_kubernetes_ingress_scheme, __address__, __meta_kubernetes_ingress_path]
            regex: (.+);(.+);(.+)
            replacement: ${1}://${2}${3}
            target_label: __param_target
          - source_labels: [__meta_kubernetes_ingress_scheme, __address__, __meta_kubernetes_ingress_annotation_prometheus_io_probe_path]
            regex: (.+);(.+);(.+)
            replacement: ${1}://${2}${3}
            target_label: __param_target
          - target_label: __address__
            replacement: ssl-exporter.{{ .Release.Namespace }}.svc.cluster.local:9219
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_ingress_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_ingress_name]
            target_label: kubernetes_name
          - regex: "app_kubernetes_io_(managed_by|version)"
            action: labeldrop
          - regex: "helm_sh_chart"
            action: labeldrop
        - job_name: kube-state-metrics
          metrics_path: /metrics
          static_configs:
          - targets:
            - 'kube-state-metrics.{{ .Release.Namespace }}.svc.cluster.local:8080'
          metric_relabel_configs:
          - source_labels: [node]
            regex: '(.+)'
            replacement: '$1'
            target_label: host
          - source_labels: [label_receiver]
            regex: '(.+)'
            replacement: '$1'
            target_label: receiver
          - regex: "label_receiver"
            action: labeldrop
          - source_labels: [label_osc_edu_role]
            regex: '(.+)'
            replacement: '$1'
            target_label: osc_edu_role
          - regex: "label_osc_edu_role"
            action: labeldrop
        - job_name: kube-state-metrics-telemetry
          metrics_path: /metrics
          static_configs:
          - targets:
            - 'kube-state-metrics.{{ .Release.Namespace }}.svc.cluster.local:8081'
          metric_relabel_configs:
          - source_labels: [node]
            regex: '(.+)'
            replacement: '$1'
            target_label: host

watch:
  image:
    repository: docker-registry.osc.edu/kubernetes/weaveworks/watch
    tag: master-0c44bf6
    pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 94
    runAsGroup: 94
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 50Mi

blackboxExporter:
  name: blackbox-exporter
  configName: blackbox-exporter-config
  image:
    repository: quay.io/prometheus/blackbox-exporter
    pullPolicy: IfNotPresent
    tag: "v0.24.0"
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      # Need the following if enable ICMP module
      # add:
      # - NET_RAW
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 50Mi
  service:
    type: ClusterIP
    port: 9115
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics

sslExporter:
  name: ssl-exporter
  configName: ssl-exporter-config
  rbac:
    create: false
  image:
    repository: docker-registry.osc.edu/kubernetes/ribbybibby/ssl-exporter
    pullPolicy: IfNotPresent
    tag: "2.4.2"
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 50Mi
  service:
    type: ClusterIP
    port: 9219
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics

ingressName: ingress-nginx
namespaceReaper: k8-namespace-reaper

kube-state-metrics:
  nameOverride: kube-state-metrics
  fullnameOverride: kube-state-metrics
  prometheusScrape: false
  service:
    annotations:
      prometheus.io/probe_skip: "true"
  collectors: []
  selfMonitor:
    enabled: true
    telemetryPort: 8081
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false
    runAsNonRoot: true
  nodeSelector:
    node-role.kubernetes.io/infrastructure: ''

dcgm-exporter:
  nameOverride: dcgm-exporter
  fullnameOverride: dcgm-exporter
  image:
    repository: docker-registry.osc.edu/osc/dcgm-exporter
    tag: 4.4.1-4.6.0-ubuntu22.04
  imagePullSecrets:
    - name: osc-registry
  arguments:
    - --no-hostname
  extraEnv:
    - name: "__DCGM_DBG_LVL"
      value: "NONE"
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9400'
  service:
    enable: false
    port: 9400
  serviceMonitor:
    enabled: false
  resources:
    limits:
      cpu: '2'
      memory: '1Gi'
    requests:
      cpu: '1'
      memory: '512Mi'
  nodeSelector:
    feature.node.kubernetes.io/pci-10de.present: "true"

hook:
  image:
    repository: docker-registry.osc.edu/kubernetes/portainer/kubectl-shell
    tag: '2.39.0'
