global:
  oscServiceAccount: nobody
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  storageClass: standard
  maintenanceGroups:
    - foo
    - bar
  debugGroups:
    - foobar
  alert:
    receiver: test
  ingress:
    host: webservice.example.com
appType: none
command: ['/http-echo']
args:
  - "-listen=:{{ .Values.global.service.port }}"
  - "-text=Hello World"
image:
  repository: hashicorp/http-echo
  tag: latest
envSecrets:
  TEST: secret
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
podResources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
data:
  enable: true
  size: 50Mi
mounts:
  emptyDir:
    test: /tmp/test
    foo: /tmp/bar
osc-common:
  oauth2-proxy:
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
database:
  enable: true
  mariadb:
    enable: true
    auth:
      rootPassword: secret
      database: name
      username: name
      password: secret
    primary:
      persistence:
        size: 50Mi
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
  postgresql:
    enable: true
    auth:
      postgresPassword: secret
      database: name
      username: name
      password: secret
    primary:
      persistence:
        size: 50Mi
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
