{{ if .Values.auth.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "osc-open-webui.auth.name" . }}
  labels:
    {{- include "osc-open-webui.auth.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "osc-open-webui.auth.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.ingressName }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.prometheusName }}
{{ end }}
