apiVersion: v1
kind: ConfigMap
metadata:
  name: osc-open-webui-otel
  labels:
    {{- include "osc-open-webui.config.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      transform/add_prefix:
        error_mode: ignore
        metric_statements:
          - context: metric
            statements:
              # Prepends "open.webui." to every metric name passing through this processor except osc metrics
              - set(metric.name, Concat(["open.webui", metric.name], ".")) where not IsMatch(metric.name, "^osc")

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889

    service:
      telemetry:
        logs:
          level: warn
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [transform/add_prefix, batch]
          exporters: [prometheus]
