apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osc.common.imagePullSecret.name" . }}
  labels:
    {{- include "osc-open-webui.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "osc.common.imagePullSecret" . }}
