apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: osc-open-webui-secret
  labels:
    {{- include "osc-open-webui.labels" . | nindent 4 }}
data:
  {{- include "osc-open-webui.secret.content" . | nindent 2 }}
