apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osc-open-webui.name" . }}
  labels:
    {{- include "osc-open-webui.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "osc.common.imagePullSecret.name" . }}
