global:
  imagePullSecret:
    password: OSC-IMAGE-PULL-PASSWORD
  ingress:
    host: test.example.com

sslExporter:
  rbac:
    create: true

kube-state-metrics:
  collectors:
    - nodes
    - pods
    - namespaces
  metricLabelsAllowlist:
    - pods=[account,job]
