global:
  imagePullSecret:
    password: OSC-IMAGE-PULL-PASSWORD
  ingress:
    host: test.example.com
  storageClass: standard

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 256Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi

prometheus-pushgateway:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

sslExporter:
  rbac:
    create: true

kube-state-metrics:
  collectors:
    - nodes
    - pods
    - namespaces
  metricLabelsAllowlist:
    - pods=[account,job]
