apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-statefulset-service-account
spec:
  background: false
  validationFailureAction: Enforce
  rules:
  - name: statefulset-add-service-account-webservice
    match:
      any:
        - resources:
            kinds:
            - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-scratch
          - local-ess
          - local-home
        - key: "{{`{{ serviceAccount }}`}}"
          operator: NotEquals
          value: ""
    context:
      - name: serviceAccount
        variable:
          jmesPath: request.object.metadata.labels."{{ include "osc.common.serviceAccountKey" . }}"
          default: ''
      - name: uidMap
        configMap:
          name: user-uid-map
          namespace: k8-ldap-configmap
      - name: gidMap
        configMap:
          name: user-gid-map
          namespace: k8-ldap-configmap
      - name: homeMap
        configMap:
          name: user-home-map
          namespace: k8-ldap-configmap
    mutate:
      foreach:
        - list: "request.object.spec.volumeClaimTemplates[]"
          patchesJson6902: |-
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/labels/osc.edu~1service-account
              op: add
              value: '{{`{{ serviceAccount }}`}}'
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/annotations/osc.edu~1service-account-uid
              op: add
              value: '{{`{{`}} uidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/annotations/osc.edu~1service-account-gid
              op: add
              value: '{{`{{`}} gidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/annotations/osc.edu~1home
              op: add
              value: '{{`{{`}} homeMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" | split(@, '/')[2:] | join('/', @) {{`}}`}}'
  - name: statefulset-add-service-account-paas
    match:
      any:
        - resources:
            kinds:
            - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-scratch
          - local-ess
          - local-home
        - key: "{{`{{ serviceAccount }}`}}"
          operator: NotEquals
          value: ""
    context:
      - name: serviceAccount
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
          jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
      - name: uidMap
        configMap:
          name: user-uid-map
          namespace: k8-ldap-configmap
      - name: gidMap
        configMap:
          name: user-gid-map
          namespace: k8-ldap-configmap
      - name: homeMap
        configMap:
          name: user-home-map
          namespace: k8-ldap-configmap
    mutate:
      foreach:
        - list: "request.object.spec.volumeClaimTemplates[]"
          patchesJson6902: |-
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/labels/osc.edu~1service-account
              op: add
              value: '{{`{{ serviceAccount }}`}}'
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/annotations/osc.edu~1service-account-uid
              op: add
              value: '{{`{{`}} uidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/annotations/osc.edu~1service-account-gid
              op: add
              value: '{{`{{`}} gidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/annotations/osc.edu~1home
              op: add
              value: '{{`{{`}} homeMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" | split(@, '/')[2:] | join('/', @) {{`}}`}}'
