apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-dynamo-resources
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: add-resources-to-init
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
                osc.edu/access-dynamo-platform: "true"
            operations:
            - CREATE
            - UPDATE
    mutate:
      foreach:
      - list: "request.object.spec.initContainers || []"
        preconditions:
          all:
            - key: '{{`{{ element.name }}`}}'
              operator: Equals
              value: "wait-for-leader*"
            - key: "{{`{{ element.resources.limits.cpu || '' }}`}}"
              operator: Equals
              value: ""
        patchesJson6902: |-
          - op: add
            path: /spec/initContainers/{{`{{ elementIndex }}`}}/resources/limits/cpu
            value: 1
      - list: "request.object.spec.initContainers || []"
        preconditions:
          all:
            - key: '{{`{{ element.name }}`}}'
              operator: Equals
              value: "wait-for-leader*"
            - key: "{{`{{ element.resources.limits.memory || '' }}`}}"
              operator: Equals
              value: ""
        patchesJson6902: |-
          - op: add
            path: /spec/initContainers/{{`{{ elementIndex }}`}}/resources/limits/memory
            value: 512Mi
      - list: "request.object.spec.initContainers || []"
        preconditions:
          all:
            - key: '{{`{{ element.name }}`}}'
              operator: Equals
              value: "wait-for-leader*"
            - key: "{{`{{ element.resources.requests.cpu || '' }}`}}"
              operator: Equals
              value: ""
        patchesJson6902: |-
          - op: add
            path: /spec/initContainers/{{`{{ elementIndex }}`}}/resources/requests/cpu
            value: 500m
      - list: "request.object.spec.initContainers || []"
        preconditions:
          all:
            - key: '{{`{{ element.name }}`}}'
              operator: Equals
              value: "wait-for-leader*"
            - key: "{{`{{ element.resources.requests.memory || '' }}`}}"
              operator: Equals
              value: ""
        patchesJson6902: |-
          - op: add
            path: /spec/initContainers/{{`{{ elementIndex }}`}}/resources/requests/memory
            value: 256Mi
