apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-statefulset-service-account
spec:
  background: false
  validationFailureAction: Enforce
  rules:
  - name: statefulset-add-service-account-webservice
    match:
      any:
        - resources:
            kinds:
            - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-scratch
          - local-ess
        - key: "{{`{{ serviceAccount }}`}}"
          operator: NotEquals
          value: ""
    context:
      - name: serviceAccount
        variable:
          jmesPath: request.object.metadata.labels."{{ include "osc.common.serviceAccountKey" . }}"
          default: ''
    mutate:
      foreach:
        - list: "request.object.spec.volumeClaimTemplates[]"
          patchesJson6902: |-
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/labels/osc.edu~1service-account
              op: add
              value: {{`{{ serviceAccount }}`}}
  - name: statefulset-add-service-account-paas
    match:
      any:
        - resources:
            kinds:
            - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-scratch
          - local-ess
        - key: "{{`{{ serviceAccount }}`}}"
          operator: NotEquals
          value: ""
    context:
      - name: serviceAccount
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
          jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
    mutate:
      foreach:
        - list: "request.object.spec.volumeClaimTemplates[]"
          patchesJson6902: |-
            - path: /spec/volumeClaimTemplates/{{`{{elementIndex}}`}}/metadata/labels/osc.edu~1service-account
              op: add
              value: {{`{{ serviceAccount }}`}}
