apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-annotations
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: paas-disable-scrape
    match:
      any:
        - resources:
            kinds:
            - Pod
            - Service
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - paas
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            prometheus.io/scrape: 'false'
