apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-role
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: paas-add-role-pod
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            osc.edu/role: paas
  - name: paas-add-role-all
    match:
      any:
        - resources:
            kinds:
            - Deployment
            - Job
            - StatefulSet
            - ReplicaSet
            - Service
            - Ingress
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            osc.edu/role: paas
