apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-image-pull-secret
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: paas-osc-registry
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - paas
      context:
      - name: secret
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}/secrets/osc-registry"
          jmesPath: "metadata.name || ''"
      preconditions:
      - key: "{{`{{ secret || '' }}`}}"
        operator: NotEquals
        value: ""
      mutate:
        patchStrategicMerge:
          spec:
            imagePullSecrets:
            - name: "{{`{{ secret }}`}}"
