apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-account
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: paas-add-account
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - paas
    preconditions:
    - key: "{{`{{ account }}`}}"
      operator: NotEquals
      value: ""
    context:
    - name: account
      apiCall:
        urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
        jmesPath: "metadata.labels.account || ''"
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            account: "{{`{{ account }}`}}"
