{{- $var := dict "registries" (list) -}}
{{- range .Values.authorizedRegistries -}}
{{- $noop := printf "%s/*" . | append $var.registries | set $var "registries" -}}
{{- end }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: authorized-registries
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: authorized-registries-users
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - "user-?*"
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    validate:
      message: >-
        Images must come from {{ join " or " $var.registries }}
      pattern:
        spec:
          containers:
            - image: "{{ join " | " $var.registries }}"
          =(initContainers):
            - image: "{{ join " | " $var.registries }}"
