apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: authorized-registries
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: authorized-registries-users
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - "user-?*"
    validate:
      message: >-
        Images must come from {{ join " or " .Values.users.authorizedRegistries }}
      anyPattern:
      {{- range .Values.users.authorizedRegistries }}
      - spec:
          containers:
            - image: "{{ . }}/* | {{ . }}:*"
          =(initContainers):
            - image: "{{ . }}/* | {{ . }}:*"
      {{- end }}
  - name: authorized-registries-webservices
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    exclude:
      any:
        - resources:
            name: "cm-acme-http-solver-*"
    validate:
      message: >-
        Images must come from {{ join " or " .Values.webservices.authorizedRegistries }}
      anyPattern:
      {{- range .Values.webservices.authorizedRegistries }}
      - spec:
          containers:
            - image: "{{ . }}/* | {{ . }}:*"
          =(initContainers):
            - image: "{{ . }}/* | {{ . }}:*"
      {{- end }}
  - name: authorized-registries-paas
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - paas
    exclude:
      any:
        - resources:
            name: "cm-acme-http-solver-*"
    validate:
      message: >-
        Images must come from {{ join " or " .Values.paas.authorizedRegistries }}
      anyPattern:
      {{- range .Values.paas.authorizedRegistries }}
      - spec:
          containers:
            - image: "{{ . }}/* | {{ . }}:*"
          =(initContainers):
            - image: "{{ . }}/* | {{ . }}:*"
      {{- end }}
