apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: authorized-registries
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: authorized-registries-users
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "user-?*"
    validate:
      message: >-
        Images must come from {{ .Values.dockerHub }} {{ if .Values.siteRegistry }}or {{ .Values.siteRegistry }}{{ end }}
      pattern:
        spec:
        {{- if .Values.siteRegistry }}
          containers:
            - image: "{{ .Values.dockerHub }}/* | {{ .Values.siteRegistry }}/*"
          =(initContainers):
            - image: "{{ .Values.dockerHub }}/* | {{ .Values.siteRegistry }}/*"
        {{- else }}
          containers:
            - image: "{{ .Values.dockerHub }}/*"
          =(initContainers):
            - image: "{{ .Values.dockerHub }}/*"
        {{- end }}
