apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    {{- include "kyverno-policies.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "kyverno.imagePullSecrets" . }}
