apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress-annotations
spec:
  background: true
  validationFailureAction: Enforce
  rules:
  - name: deny-external-dns-annotations
    match:
      any:
        - resources:
            kinds:
            - Ingress
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - paas
    validate:
      message: "External DNS annotations are now allowed"
      pattern:
        metadata:
          =(annotations):
            X(external-dns.alpha.kubernetes.io/*): "*?"
