apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: namespace-service-account
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: require-service-account
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              {{ include "osc.common.roleKey" . }}: paas
    validate:
      message: "Namespaces requires {{ include "osc.common.serviceAccountKey" . }} label be set."
      pattern:
        metadata:
          labels:
            {{ include "osc.common.serviceAccountKey" . }}: "?*"
