apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-lifetime
  namespace: kyverno
spec:
  background: true
  validationFailureAction: enforce
  rules:
  - name: pods-require-lifetime
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "user-?*"
    validate:
      message: "User pods must include an lifetime"
      pattern:
        metadata:
          annotations:
            pod.kubernetes.io/lifetime: "*?"
  - name: pods-max-lifetime
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "user-?*"
    preconditions:
    - key: "{{`{{ request.object.metadata.annotations.\"pod.kubernetes.io/lifetime\" }}`}}"
      operator: NotEquals
      value: ""
    validate:
      message: "Pod lifetime exceeds limit of 24h"
      deny:
        conditions:
        - key: "{{`{{ request.object.metadata.annotations.\"pod.kubernetes.io/lifetime\" }}`}}"
          operator: DurationGreaterThan
          value: "24h"
