apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-service-account-validation
spec:
  background: false
  validationFailureAction: Enforce
  rules:
  - name: webservice-require-service-account
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    validate:
      message: "Webservice pods must include a service account for access"
      pattern:
        metadata:
          labels:
            {{ include "osc.common.serviceAccountKey" . }}: "*?"
  - name: webservice-require-valid-service-account
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    preconditions:
    - key: "{{`{{ request.operation }}`}}"
      operator: In
      value: ["CREATE","UPDATE"]
    - key: "{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || '' {{`}}`}}"
      operator: NotEquals
      value: ""
    context:
    - name: uidMap
      configMap:
        name: user-uid-map
        namespace: k8-ldap-configmap
    - name: gidMap
      configMap:
        name: user-gid-map
        namespace: k8-ldap-configmap
    validate:
      message: >-
        Invalid service account UID or GID specified
      pattern:
        spec:
          securityContext:
            runAsNonRoot: "true"
            runAsUser: "{{`{{`}} uidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
            runAsGroup: "{{`{{`}} gidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
            fsGroup: "{{`{{`}} gidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
          =(initContainers):
            - =(securityContext):
                =(runAsUser): "{{`{{`}} uidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
                =(runAsGroup): "{{`{{`}} gidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
          containers:
            - =(securityContext):
                =(runAsUser): "{{`{{`}} uidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
                =(runAsGroup): "{{`{{`}} gidMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
  - name: webservice-service-account-authorized-for-groups
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    preconditions:
    - key: "{{`{{ request.operation }}`}}"
      operator: In
      value: ["CREATE","UPDATE"]
    - key: "{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || '' {{`}}`}}"
      operator: NotEquals
      value: ""
    - key: "{{`{{ (request.object.spec.securityContext.supplementalGroups || '').length(@) }}`}}"
      operator: GreaterThan
      value: 0
    context:
    - name: userGIDMap
      configMap:
        name: user-gids-map
        namespace: k8-ldap-configmap
    validate:
      message: "{{`{{ request.object.metadata.namespace }}`}} not authorized to use those supplemental groups"
      deny:
        conditions:
        - key: "{{`{{ request.object.spec.securityContext.supplementalGroups[*].to_string(@) }}`}}"
          operator: NotIn
          value: "{{`{{`}} userGIDMap.data.\"user-{{`{{`}} request.object.metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" {{`}}`}}\" {{`}}`}}"
  - name: paas-require-valid-service-account
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - paas
    preconditions:
    - key: "{{`{{ serviceAccount }}`}}"
      operator: NotEquals
      value: ""
    - key: "{{`{{ request.operation }}`}}"
      operator: In
      value: ["CREATE","UPDATE"]
    context:
    - name: serviceAccount
      apiCall:
        urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
        jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
    - name: uidMap
      configMap:
        name: user-uid-map
        namespace: k8-ldap-configmap
    - name: gidMap
      configMap:
        name: user-gid-map
        namespace: k8-ldap-configmap
    validate:
      message: >-
        Invalid service account UID or GID specified
      pattern:
        spec:
          securityContext:
            runAsNonRoot: "true"
            runAsUser: "{{`{{ uidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
            runAsGroup: "{{`{{ gidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
            fsGroup: "{{`{{ gidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
          =(initContainers):
            - =(securityContext):
                =(runAsUser): "{{`{{ uidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
                =(runAsGroup): "{{`{{ gidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
          containers:
            - =(securityContext):
                =(runAsUser): "{{`{{ uidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
                =(runAsGroup): "{{`{{ gidMap.data.\"user-{{ serviceAccount }}\" }}`}}"
  - name: paas-service-account-authorized-for-groups
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    preconditions:
    - key: "{{`{{ serviceAccount }}`}}"
      operator: NotEquals
      value: ""
    - key: "{{`{{ request.operation }}`}}"
      operator: In
      value: ["CREATE","UPDATE"]
    - key: "{{`{{ (request.object.spec.securityContext.supplementalGroups || '').length(@) }}`}}"
      operator: GreaterThan
      value: 0
    context:
    - name: serviceAccount
      apiCall:
        urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
        jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
    - name: userGIDMap
      configMap:
        name: user-gids-map
        namespace: k8-ldap-configmap
    validate:
      message: "{{`{{ request.object.metadata.namespace }}`}} not authorized to use those supplemental groups"
      deny:
        conditions:
        - key: "{{`{{ request.object.spec.securityContext.supplementalGroups[*].to_string(@) }}`}}"
          operator: NotIn
          value: "{{`{{ userGIDMap.data.\"user-{{ serviceAccount }}\" }}`}}"
