apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-nodeselector
spec:
  background: true
  validationFailureAction: enforce
  rules:
  - name: pod-nodeselector-user
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - "user-?*"
    validate:
      message: "Node selector must be set to ondemand"
      anyPattern:
        - spec:
            nodeSelector:
              osc.edu/role: "ondemand"
        - spec:
            nodeSelector:
              node-role.kubernetes.io/ondemand: ''
  - name: pod-nodeselector-webservice
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchExpressions:
              - key: osc.edu/role
                operator: In
                values:
                - webservice
    exclude:
      any:
        - resources:
            name: "cm-acme-http-solver-*"
    validate:
      message: "Node selector must be set"
      anyPattern:
        - spec:
            nodeSelector:
              osc.edu/role: "{{ join " | " .Values.webservices.validNodeSelector }}"
      {{- range .Values.webservices.validNodeSelector }}
        - spec:
            nodeSelector:
              node-role.kubernetes.io/{{ . }}: ''
      {{- end }}
