apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pvc-gpfs-fileset
spec:
  background: false
  validationFailureAction: Enforce
  rules:
  - name: pvc-add-scratch-user-webservice
    match:
      any:
        - resources:
            kinds:
            - PersistentVolumeClaim
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-scratch
        - key: "{{`{{ serviceAccount }}`}}"
          operator: NotEquals
          value: ""
    context:
      - name: serviceAccount
        variable:
          jmesPath: request.object.metadata.labels."{{ include "osc.common.serviceAccountKey" . }}"
          default: ''
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            osc.edu/scratch-user: "{{`{{ serviceAccount }}`}}"
  - name: pvc-add-scratch-user-paas
    match:
      any:
        - resources:
            kinds:
            - PersistentVolumeClaim
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-scratch
        - key: "{{`{{ serviceAccount }}`}}"
          operator: NotEquals
          value: ""
    context:
      - name: serviceAccount
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
          jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            osc.edu/scratch-user: "{{`{{ serviceAccount }}`}}"
  - name: validate-webservice-service-account
    match:
      any:
        - resources:
            kinds:
              - PersistentVolumeClaim
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
    validate:
      message: "PVC with osc.edu/fileset requires {{ include "osc.common.serviceAccountKey" . }} label be set."
      pattern:
        metadata:
          labels:
            {{ include "osc.common.serviceAccountKey" . }}: "?*"
  - name: pvc-validate-fileset-set
    match:
      any:
        - resources:
            kinds:
              - PersistentVolumeClaim
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
        - resources:
            kinds:
              - PersistentVolumeClaim
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
    validate:
      message: "PVC requires the osc.edu/fileset annotation to be set to a valid fileset name"
      pattern:
        metadata:
          annotations:
            osc.edu/fileset: "?*"
  - name: validate-webservice-fileset-annotation
    match:
      any:
        - resources:
            kinds:
            - PersistentVolumeClaim
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
    context:
    - name: userGroupMap
      configMap:
        name: user-all-groups-map
        namespace: k8-ldap-configmap
    validate:
      message: "PVC annotation 'osc.edu/fileset' is not authorized for this webservice"
      deny:
        conditions:
        - key: "{{`{{ request.object.metadata.annotations.\"osc.edu/fileset\" }}`}}"
          operator: AnyNotIn
          value: "{{`{{ userGroupMap.data.\"user-{{ request.object.metadata.labels.\"osc.edu/service-account\" || '' }}\" }}`}}"
  - name: validate-paas-fileset-annotation
    match:
      any:
      - resources:
          kinds:
          - PersistentVolumeClaim
          namespaceSelector:
            matchLabels:
              osc.edu/role: paas
          operations:
              - CREATE
              - UPDATE
    preconditions:
    - key: "{{`{{ request.object.metadata.annotations.\"osc.edu/fileset\" || '' }}`}}"
      operator: NotEquals
      value: ""
    - key: "{{`{{ serviceAccount }}`}}"
      operator: NotEquals
      value: ""
    context:
    - name: serviceAccount
      apiCall:
        urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
        jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
    - name: userGroupMap
      configMap:
        name: user-all-groups-map
        namespace: k8-ldap-configmap
    validate:
      message: "PVC annotation 'osc.edu/fileset' is not authorized for this namespace"
      deny:
        conditions:
        - key: "{{`{{ request.object.metadata.annotations.\"osc.edu/fileset\" }}`}}"
          operator: AnyNotIn
          value: "{{`{{ userGroupMap.data.\"user-{{ serviceAccount }}\" }}`}}"