apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: statefulset-service-account
spec:
  background: false
  validationFailureAction: Enforce
  rules:
  - name: validate-service-account
    match:
      any:
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
          - local-home
    validate:
      message: "StatefulSet using PVC with local-home, local-ess or local-scratch requires {{ include "osc.common.serviceAccountKey" . }} label be set."
      pattern:
        metadata:
          labels:
            {{ include "osc.common.serviceAccountKey" . }}: "?*"
  - name: validate-service-account-uid-gid-webservice
    match:
      any:
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
    context:
      - name: serviceAccount
        variable:
          jmesPath: request.object.metadata.labels."{{ include "osc.common.serviceAccountKey" . }}"
          default: ''
      - name: uidMap
        configMap:
          name: user-uid-map
          namespace: k8-ldap-configmap
      - name: gidMap
        configMap:
          name: user-gid-map
          namespace: k8-ldap-configmap
    validate:
      message: "StatefulSet PVC using local-ess or local-scratch requires {{ include "osc.common.serviceAccountKey" . }} annotations be set to the correct UID and GID."
      pattern:
        spec:
          =(volumeClaimTemplates):
            - (spec):
                (storageClassName): "local-ess | local-scratch"
              metadata:
                annotations:
                  osc.edu/service-account-uid: '{{`{{`}} uidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
                  osc.edu/service-account-gid: '{{`{{`}} gidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
  - name: validate-service-account-uid-gid-paas
    match:
      any:
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
    context:
      - name: serviceAccount
        apiCall:
          urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
          jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\""
      - name: uidMap
        configMap:
          name: user-uid-map
          namespace: k8-ldap-configmap
      - name: gidMap
        configMap:
          name: user-gid-map
          namespace: k8-ldap-configmap
    validate:
      message: "StatefulSet PVC using local-ess or local-scratch requires {{ include "osc.common.serviceAccountKey" . }} annotations be set to the correct UID and GID."
      pattern:
        spec:
          =(volumeClaimTemplates):
            - (spec):
                (storageClassName): "local-ess | local-scratch"
              metadata:
                annotations:
                  osc.edu/service-account-uid: '{{`{{`}} uidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
                  osc.edu/service-account-gid: '{{`{{`}} gidMap.data."user-{{`{{`}} serviceAccount {{`}}`}}" {{`}}`}}'
  - name: statefulset-validate-fileset-set
    match:
      any:
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
    validate:
      message: "StatefulSet with a PVC requires the osc.edu/fileset annotation to be set to a valid fileset name"
      pattern:
        spec:
          =(volumeClaimTemplates):
            - (spec):
                (storageClassName): "local-ess | local-scratch"
              metadata:
                annotations:
                  osc.edu/fileset: "?*"
  - name: statefulset-disallow-pde-fileset-permissions
    match:
      any:
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
        - resources:
            kinds:
              - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: paas
            operations:
              - CREATE
              - UPDATE
    preconditions:
      all:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].spec.storageClassName || '' }}`}}"
          operator: AnyIn
          value:
          - local-ess
          - local-scratch
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].metadata.annotations.\"osc.edu/fileset\" || '' }}`}}"
          operator: AnyIn
          value:
          - "PDE*"
    validate:
      message: "StatefulSet with a PVC does not allow the osc.edu/fileset annotation to be a PDE fileset and set osc.edu/volume-permission"
      pattern:
        spec:
          =(volumeClaimTemplates):
            - (spec):
                (storageClassName): "local-ess | local-scratch"
              metadata:
                annotations:
                  X(osc.edu/volume-permission): "null"
  - name: validate-webservice-fileset-annotation
    match:
      any:
        - resources:
            kinds:
            - StatefulSet
            namespaceSelector:
              matchLabels:
                osc.edu/role: webservice
            operations:
              - CREATE
              - UPDATE
    context:
    - name: userGroupMap
      configMap:
        name: user-all-groups-map
        namespace: k8-ldap-configmap
    - name: serviceAccount
      variable:
        jmesPath: request.object.metadata.labels."{{ include "osc.common.serviceAccountKey" . }}"
        default: ''
    preconditions:
    - key: "{{`{{ serviceAccount }}`}}"
      operator: NotEquals
      value: ""
    validate:
      message: "StatefulSet PVC annotation 'osc.edu/fileset' is not authorized for this webservice"
      deny:
        conditions:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].metadata.annotations.\"osc.edu/fileset\" }}`}}"
          operator: AnyNotIn
          value: "{{`{{ userGroupMap.data.\"user-{{ serviceAccount }}\" }}`}}"
  - name: validate-paas-fileset-annotation
    match:
      any:
      - resources:
          kinds:
          - StatefulSet
          namespaceSelector:
            matchLabels:
              osc.edu/role: paas
          operations:
              - CREATE
              - UPDATE
    preconditions:
    - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].metadata.annotations.\"osc.edu/fileset\" || '' }}`}}"
      operator: NotEquals
      value: ""
    - key: "{{`{{ serviceAccount }}`}}"
      operator: NotEquals
      value: ""
    context:
    - name: serviceAccount
      apiCall:
        urlPath: "/api/v1/namespaces/{{`{{ request.namespace }}`}}"
        jmesPath: "metadata.labels.\"{{ include "osc.common.serviceAccountKey" . }}\" || ''"
    - name: userGroupMap
      configMap:
        name: user-all-groups-map
        namespace: k8-ldap-configmap
    validate:
      message: "StatefulSet PVC annotation 'osc.edu/fileset' is not authorized for this namespace"
      deny:
        conditions:
        - key: "{{`{{ request.object.spec.volumeClaimTemplates[*].metadata.annotations.\"osc.edu/fileset\" }}`}}"
          operator: AnyNotIn
          value: "{{`{{ userGroupMap.data.\"user-{{ serviceAccount }}\" }}`}}"