global:
  # -- The service account used by OSC deployments.
  # Also pulled from global.env.<env>.serviceAccount
  oscServiceAccount: '{{ include "ollama.name" . }}'
  # -- The deployment's OSC environment
  environment: production
  # -- The nodeSelector role
  nodeSelectorRole: webservices
  imagePullSecret:
    # -- Create the image pull secret
    create: true
    # -- imagePullSecret name
    name: osc-registry
    # -- imagePullSecret registry
    registry: docker-registry.osc.edu
    # -- imagePullSecret username
    username: robot$webservices-read
    # -- imagePullSecret password.
    # This value will be set by OSC's Puppet.
    # This value must be set to IMAGE-PULL-PASSWORD for CI tests.
    password:
  # @ignored
  networkPolicy:
    # -- Create the network policy
    create: false
    # -- Labels for NetworkPolicy podSelector. Defaults to `"osc.common.selectorLabels"`
    podSelector: ~
    # Example define podSelector labels
    #  podSelector:
    #    app.kubernetes.io/name: test
    #
    # -- Labels of pods allowed to Ingress from the same namespace
    ingressAllowedPods: []
    # Example additional ingress labels
    #  ingressAllowedPods:
    #    - require: test
    #    - client: test
    #
    # @ignored
    ingressNamespace: ingress-nginx
    # @ignored
    prometheusNamespace: prometheus
  # @ignored
  webservicesDeploy:
    # -- Create webservices deployment rolebinding
    create: false
  # -- Groups that debug pods
  debugGroups: []
  # -- Groups that can perform maintenance operations
  maintenanceGroups: []
  # -- Groups that are allowed to perform port forwarding
  portforwardGroups: []
  auth:
    # @ignored
    enable: false
    # @ignored
    allowGroups: []
  ingress:
    # -- Ingress host
    # @default -- **required**
    host: ""
    # -- Ingress host alias
    # @default -- **required**
    hostAlias: ""
  alert:
    # -- The alert receiver
    receiver: sciapps
  # -- The service project
  # @default -- **required**
  project: ''

ollama:
  networkPolicy:
    # -- Array of additional pod labels to allow
    allowedPodLabels: []

  imagePullSecrets:
  - name: osc-registry

  image:
    repository: docker-registry.osc.edu/kubernetes/ollama/ollama
    tag: ''

  ollama:
    mountPath: /ollama
    gpu:
      enabled: true
      type: nvidia
      number: 1
    models:
      pull: []

  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-PCIE-40GB-MIG-1g.5gb

  service:
    annotations:
      prometheus.io/probe_module: http
      prometheus.io/probe_scheme: http

  podSecurityContext:
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    privileged: false

  resources:
    limits:
      memory: 8Gi
      cpu: 4
    requests:
      memory: 4Gi
      cpu: 2

  extraEnv:
  - name: OLLAMA_MODELS
    value: /ollama
  - name: HOME
    value: /ollama
  - name: OLLAMA_FLASH_ATTENTION
    value: '1'

  persistentVolume:
    enabled: true
    accessModes:
    - ReadWriteMany
    annotations:
      osc.edu/fileset: '{{ .Values.global.project }}'
    size : 500Gi
    storageClass: local-scratch

  serviceAccount:
    create: false
