global:
  environment: dev
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
webservice:
  ingress:
    host: test.local
  mounts:
    roDir:
      project: null
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 5
  auth:
    oidcIssuerURL: http://keycloak-http.keycloak.svc.cluster.local/auth/realms/master
    cookieSecret: KMdIWJeLDNssdLoaXxiLBw==
