global:
  environment: dev
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  env:
    dev:
      podResources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
webservice:
  ingress:
    host: test.local
  mounts:
    roDir:
      project: null
  auth:
    oidcIssuerURL: http://keycloak.keycloak.svc.cluster.local/realms/master
    cookieSecret: KMdIWJeLDNssdLoaXxiLBw==
