global:
  oscServiceAccount: test
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  auth:
    enable: true
    upstream: http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:80
oauth2-proxy:
  ingress:
    enabled: false
