dnsSecret: changeme

external-dns:
  provider: rfc2136
  sources:
    - service
    - ingress
  extraArgs:
    - --rfc2136-port=53
    - --rfc2136-tsig-secret=$(DNS_SECRET)
    - --rfc2136-tsig-secret-alg=hmac-sha256
    - --rfc2136-tsig-axfr
    - --metrics-address=:7979
  env:
    - name: DNS_SECRET
      valueFrom:
        secretKeyRef:
          name: external-dns
          key: secret
  service:
    port: 7979
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /metrics
      prometheus.io/probe_module: http-healthz
      prometheus.io/probe_path: /healthz
  resources:
    limits:
      cpu: 1
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
