apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.blackboxExporter.configName }}
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "configs/blackbox-exporter.yaml").AsConfig | indent 2 }}
