kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.blackboxExporter.name }}
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "blackbox-exporter.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "blackbox-exporter.selectorLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          {{- include "prometheus.selectorLabels" . | nindent 10 }}
