kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ index .Values "kube-state-metrics" "fullnameOverride" }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kube-state-metrics.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "prometheus.selectorLabels" . | nindent 10 }}
