kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.kubeSummary.name }}
  labels:
    {{- include "kube-summary-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kube-summary-exporter.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus-blackbox-exporter
    - podSelector:
        matchLabels:
          {{- include "prometheus.selectorLabels" . | nindent 10 }}
