apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
  labels:
    {{- include "prometheus-proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-proxy.selectorLabels" . | nindent 4 }}
