apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.sslExporter.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ssl-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNamespaces:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    interval: 60s
    path: /metrics
