apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sslExporter.configName }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "configs/ssl-exporter.yaml").AsConfig | indent 2 }}
