global:
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: webservices
  ingress:
    host: webservice.k8.example.com
    hostAlias: webservice.example.com
  webui_secret_key: supersecret
osc-open-webui:
  ollama:
    networkPolicy:
      allowedPodLabels:
        - app.kubernetes.io/name: ollama
  open-webui:
    persistence:
      storageClass: standard
      size: 50Mi
    copyAppData:
      command:
        - sh
        - '-c'
        - exit
        - '0'
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        memory: 200Mi
        cpu: 500m
    ollama:
      ollama:
        gpu:
          enabled: false
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 200Mi
          cpu: 500m
      volumes:
      - name: data
        hostPath:
          path: /tmp
          type: Directory
      - name: home
        hostPath:
          path: /tmp
          type: Directory
      tests:
        # The tests aren't configurable and violate Kyverno policies
        enabled: false
