apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "webservice.authSecretName" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
data:
  {{- with .Values.auth.clientSecret }}
  client-secret: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.auth.cookieSecret }}
  cookie-secret: {{ . | b64enc | quote }}
  {{- end }}
