{{ if .Values.auth.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webservice.auth.name" . }}
  labels:
    {{- include "webservice.auth.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.auth.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.hostAlias }}
    nginx.ingress.kubernetes.io/server-alias: {{ .Values.ingress.hostAlias }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
  {{- if .Values.ingress.hostAlias }}
    - {{ .Values.ingress.hostAlias | quote }}
  {{- end }}
    secretName: {{ include "webservice.name" . }}-cert
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: {{ include "webservice.auth.name" . }}
            port:
              number: {{ .Values.auth.service.port }}
      - path: /ping
        pathType: Prefix
        backend:
          service:
            name: {{ include "webservice.auth.name" . }}
            port:
              number: {{ .Values.auth.service.port }}
{{ end }}
