{{ if .Values.auth.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "webservice.auth.name" . }}
  labels:
    {{- include "webservice.auth.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "webservice.auth.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.ingressName }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.prometheusName }}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.blackboxExporterName }}
{{ end }}
