---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webservice.name" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
  {{- if (include "webservice.alert.receiver" .) }}
    receiver: {{ include "webservice.alert.receiver" . }}
  {{- end }}
  annotations:
    prometheus.io/probe_scheme: 'https'
    cert-manager.io/cluster-issuer: letsencrypt
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.auth.enable }}
    {{- with .Values.auth.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if (include "webservice.ingressHostAlias" .) }}
    nginx.ingress.kubernetes.io/server-alias: {{ tpl (include "webservice.ingressHostAlias" .) . }}
    {{- end }}
    {{- if eq .Values.appType "rshiny" }}
      {{- toYaml .Values.ingress.rShinyAnnotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ required "Must provide ingress host" (tpl (include "webservice.ingressHost" .) .) | quote }}
  {{- if (include "webservice.ingressHostAlias" .) }}
    - {{ tpl (include "webservice.ingressHostAlias" .) . | quote }}
  {{- end }}
    secretName: {{ include "webservice.name" . }}-cert
  rules:
  - host: {{ tpl (include "webservice.ingressHost" .) . | quote }}
    http:
      paths:
      {{ $root := . }}
      {{- range $idx, $container := .Values.containers }}
      - path: {{ $container.ingressPath }}
        pathType: Prefix
        backend:
          service:
          {{- if and (ne $container.auth false) (eq $root.Values.auth.enable true) }}
            name: {{ include "webservice.auth.name" $root }}
            port:
              number: {{ $root.Values.auth.service.port }}
          {{- else }}
            name: {{ include "webservice.name" $root }}
            port:
              number: {{ $container.port | default (add $root.Values.service.port $idx) }}
          {{- end }}
      {{- end }}
