apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webservice.name" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.auth.enable }}
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    {{- end }}
    {{- if .Values.ingress.hostAlias }}
    nginx.ingress.kubernetes.io/server-alias: {{ tpl .Values.ingress.hostAlias . }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ required "Must provide ingress host" (tpl .Values.ingress.host .) | quote }}
  {{- if .Values.ingress.hostAlias }}
    - {{ tpl .Values.ingress.hostAlias . | quote }}
  {{- end }}
    secretName: {{ include "webservice.name" . }}-cert
  rules:
  - host: {{ tpl .Values.ingress.host . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "webservice.name" . }}
            port:
              number: {{ .Values.service.port }}
