{{- if or .Values.secrets .Values.database.mariadb.enable .Values.database.postgresql.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webservice.name" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
type: Opaque
data:
{{- if or .Values.database.mariadb.enable .Values.database.postgresql.enable }}
  database-password: {{ include "webservice.database.password" . | b64enc | quote }}
{{- end }}
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- range $k, $v := .Values.envSecrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- end }}
