{{- if .Values.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webservices.serviceAccountName" . }}
  labels:
    {{- include "webservices.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
