apiVersion: v1
kind: Service
metadata:
  name: {{ include "webservice.name" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
  {{- if (include "webservice.alert.receiver" .) }}
    receiver: {{ include "webservice.alert.receiver" . }}
  {{- end }}
  {{- if or .Values.service.annotations (index .Values.service.typeAnnotations .Values.appType) }}
  annotations:
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with index .Values.service.typeAnnotations .Values.appType }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ports:
  {{ $root := . }}
  {{- range $idx, $container := .Values.containers }}
  - name: {{ $container.portName | default (tpl $container.name $root)  }}
    port: {{ $container.port | default (add $root.Values.service.port $idx) }}
    protocol: TCP
    targetPort: {{ $container.portName | default (tpl $container.name $root)  }}
  {{- end }}
  selector:
    {{- include "webservice.selectorLabels" $root | nindent 4 }}
  type: ClusterIP
