apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webservice.name" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "osc.common.imagePullSecret.name" . }}
