apiVersion: v1
kind: Service
metadata:
  name: {{ include "hpcgpt-mcp.fullname" . }}-chat
  labels:
    {{- include "hpcgpt-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: osc_chat
    receiver: '{{ index .Values.global.alert.receiver }}'
spec:
  type: {{ .Values.osc_chat.service.type }}
  ports:
    - port: {{ .Values.osc_chat.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hpcgpt-mcp.osc_chat.selectorLabels" . | nindent 4 }}
