apiVersion: v2
name: cryosparc
description: OSC CryoSPARC bootstrap Helm Chart
type: application
version: 0.5.0
appVersion: "4.7.1-r3"
maintainers:
  - name: zyou
dependencies:
  - name: osc-common
    version: 0.13.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../osc-common
