global:
  oscServiceAccount: nobody
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  storageClass: standard
  maintenanceGroups:
    - testgroup
  portforwardGroups:
    - testgroup1
  mongodb:
    auth:
      rootPassword: supersecret
mongodb:
  enable: true
  containerSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
  podSecurityContext:
    fsGroup: 65534
  persistence:
    size: 50Mi
    accessModes:
    - ReadWriteOnce
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  backup:
    cronjob:
      schedule: '* * * * *'
      containerSecurityContext:
        runAsUser: 65534
        runAsGroup: 65534
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 128Mi
      storage:
        accessModes:
        - ReadWriteOnce
  metrics:
    password: metricssecret
