{{- $apiKey := .Values.backend.apiKey }}
{{- if not $apiKey }}
{{- $apiKey = randAlphaNum 32 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regression-logging.fullname" . }}-api-key
  labels:
    {{- include "regression-logging.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $apiKey | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "regression-logging.fullname" . }}-frontend-config
  labels:
    {{- include "regression-logging.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "apiKey": "{{ $apiKey }}"
    }
