{{- $fullName := include "regression-logging.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-backend
  labels:
    {{- include "regression-logging.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "regression-logging.labels" . | nindent 4 }}
    component: backend
