{{- $fullName := include "regression-logging.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-backend
  labels:
    {{- include "regression-logging.labels" . | nindent 4 }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "regression-logging.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "regression-logging.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret.name }}
      containers:
        - name: backend
          image: {{ include "regression-logging.image" (dict "imageRoot" .Values.backend.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MONGODB_URI
              value: "mongodb://{{ .Values.database.mongodb.service.nameOverride }}:{{ .Values.database.mongodb.service.ports.mongodb }}"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "regression-logging.fullname" . }}-api-key
                  key: api-key
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      nodeSelector:
        '{{ include "osc.common.nodeSelectorRoleKey" . }}': ''
