{{- $fullName := include "regression-logging.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-frontend
  labels:
    {{- include "regression-logging.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "regression-logging.labels" . | nindent 4 }}
    component: frontend
