global:
  environment: dev
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  env:
    dev:
      podResources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 128m
          memory: 265Mi
  ingress:
    host: test.local
webservice:
  mounts:
    rwDir: null
