apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hfToken.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynamo.labels" . | nindent 4 }}
type: Opaque
data:
  HF_TOKEN: {{ required "Huggingface token is required in hfToken" .Values.hfToken.value | b64enc }}
