apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns.fullname" . }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "external-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "external-dns.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "external-dns.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.config.dnsSecret }}
          - name: DNS_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "external-dns.fullname" . }}
                key: secret
          {{- end }}
          args:
          {{- if .Values.config.ownerID }}
          - --txt-owner-id={{ .Values.config.ownerID }}
          {{- end }}
          - --provider=rfc2136
          {{- if .Values.config.dnsMaster }}
          - --rfc2136-host={{ .Values.config.dnsMaster }}
          {{- end }}
          - --rfc2136-port=53
          {{- if .Values.config.domain }}
          - --rfc2136-zone={{ .Values.config.domain }}
          {{- end }}
          {{- if .Values.config.dnsSecret }}
          - --rfc2136-tsig-secret=$(DNS_SECRET)
          {{- end }}
          - --rfc2136-tsig-secret-alg=hmac-sha256
          {{- if .Values.config.keyname }}
          - --rfc2136-tsig-keyname={{ .Values.config.keyname }}
          {{- end }}
          - --rfc2136-tsig-axfr
          - --source=ingress
          - --source=service
          {{- if .Values.config.domain }}
          - --domain-filter={{ .Values.config.domain }}
          {{- end }}
          {{- if .Values.config.excludeDomain }}
          - --exclude-domains={{ .Values.config.excludeDomain }}
          {{- end }}
          - --metrics-address=:{{ .Values.service.port }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
