apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: external-dns
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
data:
  {{- if .Values.dnsSecret }}
  secret: |-
    {{ .Values.dnsSecret | b64enc }}
  {{- end }}
