apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "external-dns.fullname" . }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
data:
  {{- if .Values.config.dnsSecret }}
  secret: |-
    {{ .Values.config.dnsSecret | b64enc }}
  {{- end }}
