global:
  environment: dev
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  ingress:
    host: test.local
webservice:
  podResources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

osc-common:
  oauth2-proxy:
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
