global:
  environment: dev
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  ingress:
    host: test.local
webservice:
  podResources:
    limits:
      cpu: 1
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 256Mi
