apiVersion: v2
name: osc-common
description: OSC common Helm Chart
type: application
version: 0.10.1
appVersion: "0.1.0"
maintainers:
  - name: treydock
dependencies:
  - name: oauth2-proxy
    version: 10.3.0
    repository: https://oauth2-proxy.github.io/manifests
    condition: global.auth.enable
