apiVersion: v2
name: osc-common
description: OSC common Helm Chart
type: application
version: 0.12.2
appVersion: "0.1.0"
maintainers:
  - name: treydock
dependencies:
  - name: oauth2-proxy
    # version: 10.3.0
    # repository: https://oauth2-proxy.github.io/manifests
    # Use local copy until merged and released:
    # https://github.com/oauth2-proxy/manifests/pull/400
    repository: oci://docker-registry.osc.edu/kubernetes
    version: 10.4.0-osc-r1
    condition: global.auth.enable
