global:
  environment: ""
  imageTag: v1.0.0
  env:
    production:
      serviceAccount: nfsnobody
      image:
        tag: '{{ .Values.global.imageTag }}'
      service:
        alert:
          receiver: shiny-sir
    test:
      serviceAccount: nfsnobody
      image:
        tag: '{{ .Values.global.imageTag }}'
      service:
        alert:
          receiver: shiny-sir
      podResources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    dev:
      serviceAccount: nfsnobody
      image:
        tag: latest
      service:
        alert:
          receiver: shiny-sir
      podResources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
webservice:
  appType: rshiny
  auth:
    enable: false
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/sirmodel
