global:
  environment: ""
  imageTag: v1.1.0
  env:
    production:
      serviceAccount: k8spublic
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    test:
      serviceAccount: k8spublic
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    dev:
      serviceAccount: k8spublic
      replicas: 1
      image:
        tag: latest
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
webservice:
  appType: rshiny
  auth:
    enable: false
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/sirmodel
  alert:
    receiver: shiny-sir
  debugGroups:
    - wiagstf
