global:
  environment: ""
  imageTag: v1.1.0
  env:
    production:
      serviceAccount: nfsnobody
      image:
        tag: '{{ .Values.global.imageTag }}'
    test:
      serviceAccount: nfsnobody
      image:
        tag: '{{ .Values.global.imageTag }}'
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    dev:
      serviceAccount: nfsnobody
      image:
        tag: latest
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
webservice:
  appType: rshiny
  auth:
    enable: false
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/sirmodel
  service:
    alert:
      receiver: shiny-sir
