apiVersion: v2
name: nominatim
description: OSC Nominatim service
type: application
version: 0.1.0
appVersion: "4.0"
maintainers:
  - name: treydock
dependencies:
  - name: osc-common
    version: 0.5.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../../charts/osc-common
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: nominatim
    version: 2.0.0-rc9
    repository: https://treydock.github.io/robjuz-helm-charts/
    # repository: https://robjuz.github.io/helm-charts/
    # repository: file://../../../robjuz-helm-charts/charts/nominatim
