kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "nominatim.name" . }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nominatim.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.ingressName }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.prometheusName }}
