apiVersion: v2
name: paas
description: OSC PAAS bootstrap Helm Chart
type: application
version: 0.5.0
appVersion: "0.1.0"
maintainers:
  - name: treydock
dependencies:
  - name: osc-common
    version: 0.7.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../osc-common
