---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "paas.name" . }}
  labels:
    {{- include "paas.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods/log
    - events
  verbs:
    - get
    - list
- apiGroups: [""]
  resources:
    - pods
    - pods/exec
    - services
    - configmaps
    - serviceaccounts
    - secrets
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
- apiGroups: ["apps"]
  resources:
    - deployments/scale
  verbs:
    - get
    - patch
    - update
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - networkpolicies
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
{{ if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
- apiGroups: ["cert-manager.io"]
  resources:
    - certificates
    - certificaterequests
  verbs:
    - get
    - list
    - watch
{{ end -}}
{{ if .Capabilities.APIVersions.Has "acme.cert-manager.io/v1" -}}
- apiGroups: ["acme.cert-manager.io"]
  resources:
    - orders
    - challenges
  verbs:
    - get
    - list
    - watch
{{ end -}}
