{{ range $namespace := .Values.namespaces }}
{{ if $namespace.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.imagePullSecret.name }}
  namespace: {{ $namespace.name }}
  labels:
    {{- include "paas.namespaced.labels" (list $namespace $) | nindent 4 }}
  annotations:
    {{- include "paas.namespaced.annotations" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "paas.imagePullSecret" (list $namespace $) }}
{{ end }}
{{ end }}
