{{ range $namespace := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "Namespace 'name' is required" $namespace.name }}
  labels:
    {{- include "paas.namespaced.labels" (list $namespace $) | nindent 4 }}
    app.kubernetes.io/name: {{ $namespace.name }}
    osc.edu/role: paas
    {{ include "osc.common.serviceAccountKey" . }}: {{ required "Namespace 'serviceAccount' is required" $namespace.serviceAccount}}
    account: {{ required "Namespace 'account' is required" $namespace.account }}
  annotations:
    {{- include "paas.namespaced.annotations" $ | nindent 4 }}
    {{- with $namespace.allowedDNS }}
    osc.edu/allowed-dns: {{ join "," . | quote }}
    {{- end }}
    {{- if ne $namespace.collectLogs true }}
    splunk.com/exclude: "true"
    {{- end }}
    {{- if eq $namespace.allowNodeport true }}
    osc.edu/allow-nodeport: "true"
    {{- end }}
{{ end }}
