{{ range $namespace := .Values.namespaces }}
{{ $gpuLimit := $namespace.gpuLimit | default dict }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ $namespace.name }}-resourcequota
  namespace: {{ $namespace.name }}
  labels:
    {{- include "paas.namespaced.labels" (list $namespace $) | nindent 4 }}
  annotations:
    {{- include "paas.namespaced.annotations" $ | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ $namespace.cpuLimit | default $.Values.default.cpuLimit | quote }}
    requests.memory: {{ $namespace.memoryLimit | default $.Values.default.memoryLimit | quote }}
    requests.nvidia.com/mig-1g.5gb: {{ index $gpuLimit "mig-1g.5gb" | default (index $.Values.default.gpuLimit "mig-1g.5gb") | quote }}
    requests.nvidia.com/mig-3g.20gb: {{ index $gpuLimit "mig-3g.20gb" | default (index $.Values.default.gpuLimit "mig-3g.20gb") | quote }}
    requests.nvidia.com/mig-7g.40gb: {{ index $gpuLimit "mig-7g.40gb" | default (index $.Values.default.gpuLimit "mig-7g.40gb") | quote }}
    limits.cpu: {{ $namespace.cpuLimit | default $.Values.default.cpuLimit | quote }}
    limits.memory: {{ $namespace.memoryLimit | default $.Values.default.memoryLimit | quote }}
    limits.nvidia.com/mig-1g.5gb: {{ index $gpuLimit "mig-1g.5gb" | default (index $.Values.default.gpuLimit "mig-1g.5gb") | quote }}
    limits.nvidia.com/mig-3g.20gb: {{ index $gpuLimit "mig-3g.20gb" | default (index $.Values.default.gpuLimit "mig-3g.20gb") | quote }}
    limits.nvidia.com/mig-7g.40gb: {{ index $gpuLimit "mig-7g.40gb" | default (index $.Values.default.gpuLimit "mig-7g.40gb") | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ $namespace.name }}-limitrange
  namespace: {{ $namespace.name }}
  labels:
    {{- include "paas.namespaced.labels" (list $namespace $) | nindent 4 }}
  annotations:
    {{- include "paas.namespaced.annotations" $ | nindent 4 }}
spec:
  limits:
    - default:
        cpu: {{ $namespace.cpuDefault | default $.Values.default.cpu | quote }}
        memory: {{ $namespace.memoryDefault | default $.Values.default.memory | quote }}
      defaultRequest:
        cpu: {{ $namespace.cpuDefault | default $.Values.default.cpu | quote }}
        memory: {{ $namespace.memoryDefault | default $.Values.default.memory | quote }}
      type: Container
{{ end }}
