global:
  environment: ""
  imageTag: v0.2.0
  env:
    production:
      serviceAccount: immunegenetics
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    test:
      serviceAccount: immunegenetics
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
    dev:
      serviceAccount: immunegenetics
      replicas: 1
      image:
        tag: latest
webservice:
  appType: rshiny
  auth:
    enable: false
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/rigatoni
  mounts:
    roDir:
      project: /fs/ess/PAS0854
  debugGroups:
    - wiagstf
    - PAS0854
