{{- if .Values.global.database.allowIngress }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "database.name" . }}-ingress
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "database.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.global.ingressName }}
{{- end }}
