ARG UNPATCHED_IMAGE
FROM ${UNPATCHED_IMAGE}
LABEL maintainer='Zhi-Qiang You <zyou@osc.edu>'

COPY cryosparc_master_patch.tar.gz /tmp/patch.tar.gz

RUN ls -1 /tmp/patch.tar.gz && \
    tar xvf /tmp/patch.tar.gz -C /opt && \
    rm -rf /tmp/*

WORKDIR /opt/cryosparc_master
