global:
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  storageClass: standard
nominatim:
  nominatimInitialize:
    enabled: false
    # enabled: true
    importStyle: admin
  nominatimReplications:
    enabled: false
    # enabled: true
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 256Mi
  nominatimReplications:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 256Mi
  ingress:
    hostname: test.local
  projectDir:
    size: 500Mi
  postgresql:
    # diagnosticMode:
    #   enabled: true
    primary:
      persistence:
        size: 500Mi
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 256Mi
