name: Test Helm

on:
  pull_request:
    paths:
      - charts/**
      - .github/workflows/test.yaml

jobs:
  test-helm:
    runs-on: ubuntu-latest
    name: Test Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/cf.yaml --chart-dirs charts
      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.14.0
          cluster_name: kind
          node_image: kindest/node:v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae
          config: .github/config/kind.yaml
      - name: Build and Load images
        run: |
          make -f docker-images/mariadb/Makefile build
          make -f docker-images/mariadb/Makefile kind-load
          make -f docker-images/postgresql/Makefile build
          make -f docker-images/postgresql/Makefile kind-load
      - name: Label kind nodes
        run: |
          kubectl label node kind-worker node-role.kubernetes.io/test=''
          kubectl label node kind-worker2 node-role.kubernetes.io/test=''
      - name: Set image pull secret
        run: |
          sed -i 's|IMAGE-PULL-PASSWORD|${{ secrets.OSC_REGISTRY_ROBOT_WEBSERVICES_READ_TOKEN}}|g' charts/*/ci/*.yaml
      - name: Install Keycloak
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install keycloak bitnami/keycloak -n keycloak --create-namespace --version 9.2.2
      - name: Install Kyverno
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno kyverno/kyverno -n kyverno --create-namespace
      - name: Run chart-testing (install)
        run: ct install --config .github/config/cf.yaml
      - name: Debug failure
        if: failure()
        run: |
          kubectl describe pod -A
          kubectl describe service -A
          kubectl describe daemonset -A
