name: Test Private Helm

on:
  pull_request:
    paths:
      - charts-private/**
      - .github/workflows/test-private.yaml

jobs:
  test-helm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart:
          - "phylogatr-web"
          - "focalmap"
          - "sirmodel"
    name: Test Helm Chart ${{ matrix.chart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/cf.yaml --charts charts-private/${{ matrix.chart }}
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.11.1
          cluster_name: kind
          node_image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - name: Label kind node
        run: kubectl label node kind-control-plane osc.edu/role=test
      - name: Set image pull secret
        run: |
          sed -i 's|IMAGE-PULL-PASSWORD|${{ secrets.OSC_REGISTRY_ROBOT_WEBSERVICES_READ_TOKEN}}|g' charts-private/${{ matrix.chart }}/ci/*.yaml
      - name: Install Keycloak
        run: |
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm install keycloak codecentric/keycloak -n keycloak --create-namespace --version 9.9.2 --values .github/config/keycloak-values.yaml
      - name: Install Kyverno
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno kyverno/kyverno -n kyverno --create-namespace -f .github/config/kyverno-values.yaml
          helm dependency build charts/kyverno-policies
          helm install kyverno-policies charts/kyverno-policies -n kyverno -f .github/config/kyverno-policies-values.yaml
          kubectl apply -f .github/config/k8-ldap-configmaps.yaml
          timeout 60 /bin/bash -c 'until kubectl get pods -n kyverno -o jsonpath="{.items[0].status.phase}" | grep Running ; do echo "Waiting for Kyverno" ; sleep 10 ; done'
          sleep 60
      - name: Add namespaces
        run: kubectl apply -f .github/config/namespaces.yaml
      - name: Run chart-testing (install)
        run: |
          ct install --config .github/config/cf.yaml --charts charts-private/${{ matrix.chart }} --namespace ${{ matrix.chart }}
      - name: Debug failure
        if: failure()
        run: |
          kubectl describe pod -A
          kubectl describe service -A
          kubectl describe daemonset -A
          kubectl logs $(kubectl get pods -n kyverno -o jsonpath="{.items[0].metadata.name}") -n kyverno
