name: Test Kyverno

on:
  pull_request:
    paths:
      - Makefile
      - charts/kyverno-policies/**
      - tests/kyverno-policies/**
      - .github/workflows/test-kyverno.yaml

jobs:
  test-kyverno-policies:
    runs-on: ubuntu-latest
    name: Test Kyverno policies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
          cache: false
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Test Kyverno policies
        run: |
          helm dependency update charts/kyverno-policies
          make kyverno-test
