name: Test Helm

on:
  pull_request:

jobs:
  test-helm:
    runs-on: ubuntu-latest
    name: Test Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Decrypt private values
        run: |
          gpg --version
          make decrypt-private-values
        env:
          OSC_PRIVATE_CHARTS_GPG_PASSPHRASE: ${{ secrets.OSC_PRIVATE_CHARTS_GPG_PASSPHRASE }}
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/cf.yaml --chart-dirs charts,charts-private
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/config/cf.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.11.1
          cluster_name: kind
          node_image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - name: Build and Load mariadb image
        run: |
          make -f docker-images/mariadb/Makefile build
          make -f docker-images/mariadb/Makefile kind-load
      - name: Install Keycloak
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm install keycloak codecentric/keycloak -n keycloak --create-namespace --version 9.9.2 --values .github/config/keycloak-values.yaml
      - name: Install Kyverno
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno kyverno/kyverno -n kyverno --create-namespace
      - name: Run chart-testing (install)
        run: ct install --config .github/config/cf.yaml
        if: steps.list-changed.outputs.changed == 'true'
      - name: Debug failure
        if: failure()
        run: |
          kubectl describe pod -A
          kubectl describe service -A
          kubectl describe daemonset -A
