name: Test Helm

on:
  pull_request:
    paths:
      - charts/**
      - .github/workflows/test.yaml

jobs:
  test-helm:
    runs-on: ubuntu-latest
    name: Test Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/cf.yaml --chart-dirs charts
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.11.1
          cluster_name: kind
          node_image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
      - name: Build and Load mariadb image
        run: |
          make -f docker-images/mariadb/Makefile build
          make -f docker-images/mariadb/Makefile kind-load
      - name: Label kind node
        run: kubectl label node kind-control-plane osc.edu/role=test
      - name: Set image pull secret
        run: |
          sed -i 's|IMAGE-PULL-PASSWORD|${{ secrets.OSC_REGISTRY_ROBOT_WEBSERVICES_READ_TOKEN}}|g' charts/*/ci/*.yaml
      - name: Install Keycloak
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install keycloak bitnami/keycloak -n keycloak --create-namespace --version 9.2.2
      - name: Install Kyverno
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm install kyverno kyverno/kyverno -n kyverno --create-namespace
      - name: Run chart-testing (install)
        run: ct install --config .github/config/cf.yaml
      - name: Debug failure
        if: failure()
        run: |
          kubectl describe pod -A
          kubectl describe service -A
          kubectl describe daemonset -A
