name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-helm:
    runs-on: ubuntu-latest
    name: Test Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/cf.yaml
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/config/cf.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Create kind cluster
        uses: container-tools/kind-action@v1
        if: steps.list-changed.outputs.changed == 'true'
      - name: Install Keycloak
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm install keycloak codecentric/keycloak -n keycloak --create-namespace --version 9.9.2 --values .github/config/keycloak-values.yaml
      - name: Run chart-testing (install)
        run: ct install --config .github/config/cf.yaml
        if: steps.list-changed.outputs.changed == 'true'
