global:
  environment: ""
  imageTag: v2.4.0
  env:
    production:
      serviceAccount: focalmap
      image:
        tag: '{{ .Values.global.imageTag }}'
      service:
        alert:
          receiver: covidsim
      podResources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 1
          memory: 256Mi
    test:
      serviceAccount: focalmap
      image:
        tag: '{{ .Values.global.imageTag }}'
      service:
        alert:
          receiver: gateways
      podResources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 1
          memory: 256Mi
    dev:
      serviceAccount: focalmapdev
      image:
        tag: latest
      service:
        alert:
          receiver: gateways
      podResources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 1
          memory: 256Mi
webservice:
  appType: rshiny
  auth:
    enable: true
    accessGroup: PDE0006
    idpHost: EXTERNAL-DATA
    clientSecret: EXTERNAL-SECRET
    cookieSecret: EXTERNAL-SECRET
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/focalmap
  mounts:
    roDir:
      project: /fs/ess/PDE0001
  debugGroups:
    - focalmap_developer
    - wiagstf
