global:
  environment: ""
  imageTag: v0.6.0
  env:
    production:
      serviceAccount: focalmap
      image:
        tag: '{{ .Values.global.imageTag }}'
      service:
        alert:
          receiver: covidsim
    test:
      serviceAccount: focalmap
      image:
        tag: '{{ .Values.global.imageTag }}'
      service:
        alert:
          receiver: gateways
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    dev:
      serviceAccount: focalmapdev
      image:
        tag: latest
      service:
        alert:
          receiver: gateways
      podResources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
webservice:
  appType: rshiny
  auth:
    enable: true
    accessGroup: PDE0006
    idpHost: EXTERNAL-DATA
    clientSecret: EXTERNAL-SECRET
    cookieSecret: EXTERNAL-SECRET
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/focalmap
  mounts:
    roDir:
      project: /fs/ess/PDE0001
