global:
  environment: ""
  imageTag: v2.4.0
  env:
    production:
      serviceAccount: focalmap
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
      alert:
        receiver: covidsim
      podResources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 1
          memory: 256Mi
      auth:
        replicas: 2
    test:
      serviceAccount: focalmap
      replicas: 2
      image:
        tag: '{{ .Values.global.imageTag }}'
      alert:
        receiver: gateways
      podResources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 1
          memory: 256Mi
      auth:
        replicas: 2
    dev:
      serviceAccount: focalmapdev
      replicas: 1
      image:
        tag: latest
      alert:
        receiver: gateways
      podResources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 1
          memory: 256Mi
      auth:
        replicas: 1
webservice:
  appType: rshiny
  auth:
    enable: true
    accessGroup: PDE0006
    idpHost: EXTERNAL-DATA
    clientSecret: EXTERNAL-SECRET
    cookieSecret: EXTERNAL-SECRET
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/focalmap
  mounts:
    roDir:
      project: /fs/ess/PDE0001
  debugGroups:
    - focalmap_developer
    - wiagstf
