global:
  environment: ""
  imageTag: v1.2.0
  env:
    production:
      serviceAccount: focalmap
      image:
        tag: '{{ .Values.global.imageTag }}'
    test:
      serviceAccount: focalmap
      image:
        tag: '{{ .Values.global.imageTag }}'
    dev:
      serviceAccount: focalmapdev
      image:
        tag: latest
webservice:
  rShiny: true
  auth:
    enable: true
    accessGroup: PDE0006
    idpHost: EXTERNAL-DATA
    clientSecret: EXTERNAL-SECRET
    cookieSecret: EXTERNAL-SECRET
  command: ['/bin/passenger', 'start']
  args:
  - "--app-start-command"
  - 'R --no-save --slave -f /app/entrypoint.R --args $$PORT'
  workingDir: /app
  image:
    repository: docker-registry.osc.edu/webservices/focalmap
  mounts:
    roDir:
      project: /fs/ess/PDE0001
