global:
  # -- The service account used by OSC deployments.
  oscServiceAccount: dynamo
  # -- The deployment's OSC environment
  environment: production
  # -- The OSC node role to use with nodeSelector
  nodeSelectorRole: webservices
  imagePullSecret:
    # -- imagePullSecret name
    name: osc-registry
    # -- imagePullSecret registry
    registry: docker-registry.osc.edu
    # -- imagePullSecret username
    username: robot$webservices-read
    # -- imagePullSecret password. This value will be set by OSC's Puppet.
    # @default -- **required**
    password:
  # @ignored
  networkPolicy:
    create: false
  # @ignored
  webservicesDeploy:
    create: false
  # -- The fileset for storage
  fileset: PZS0645
  # -- The storage class to use for PV claims
  storageClass: local-ess
  ingress:
    # -- Ingress host name
    host: ""
    # -- Ingress host alias
    hostAlias: ""
  auth:
    # -- Restrict access to these groups
    allowGroups:
      - oscall
      - PZS0645
  # -- The Open WebUI secret key
  # @default -- **required**
  webui_secret_key:
  # -- Define models
  models: {}
  # Example:
  # models:
  #   qwen3:
  #     model: Qwen/Qwen3-0.6B
  #     decode:
  #       args:
  #         - --max-model-len
  #         - "20480"
  #       cpu: 2
  #       memory: 6Gi
  #       gpu: 1
  #       gpuType: NVIDIA-A100-PCIE-40GB-MIG-1g.5gb

image:
  # -- The repository path to main vllm runtime image
  repository: kubernetes/ai-dynamo/vllm-runtime
  # @ignored
  pullPolicy: IfNotPresent
  # -- The vllm runtime image tag
  # @default -- The chart's appVersion
  tag: ""
  # -- The release of the custom OSC vllm runtime image
  release: "0"

hfToken:
  # @ignored
  name: hf-token-secret
  # -- The HF token for Hugging Face
  # @default -- **required**
  value:

cache:
  # @ignored
  name: dynamo-cache
  # @ignored
  annotations:
    osc.edu/fileset: '{{ .Values.global.fileset }}'
  # @ignored
  size: 100Gi

# -- The default GPU type
defaultGpuType: NVIDIA-A100-PCIE-40GB-MIG-7g.40gb
# -- The RDMA resource name in Kubernetes
rdmaResource: rdma/shared_mlx5

# @ignored
podSecurityContext:
  runAsNonRoot: true

# @ignored
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

# @ignored
imagePuller:
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 128Mi

osc-open-webui:
  open-webui:
    # @ignored
    openaiBaseApiUrl: '{{ include "dynamo.openai.urls" . }}'
    # @ignored
    openaiApiKey: false
    image:
      # -- The version of Open WebUI
      tag: 0.9.6
    # @ignored
    persistence:
      storageClass: '{{ .Values.global.storageClass }}'
      labels:
        '{{ include "osc.common.serviceAccountKey" . }}': '{{ include "osc.common.serviceAccountValue" . }}'
      annotations:
        osc.edu/fileset: '{{ .Values.global.fileset }}'
    # @ignored
    extraEnvVars: []
    sso:
      # -- Enables role access controls in Open WebUI
      enableRoleManagement: true
    # @ignored
    ollama:
      enabled: false
