global:
  # -- The service account used by OSC deployments.
  # @default -- The chart's release name
  oscServiceAccount: '{{ include "dynamo.name" . }}'
  # -- The deployment's OSC environment
  environment: production
  # -- The OSC node role to use with nodeSelector
  nodeSelectorRole: webservices
  imagePullSecret:
    # -- imagePullSecret name
    name: osc-registry
    # -- imagePullSecret registry
    registry: docker-registry.osc.edu
    # -- imagePullSecret username
    username: robot$webservices-read
    # -- imagePullSecret password. This value will be set by OSC's Puppet.
    # @default -- **required**
    password:
  # @ignored
  networkPolicy:
    create: false
  # @ignored
  webservicesDeploy:
    create: false

image:
  # -- The repository path to main vllm runtime image
  repository: kubernetes/ai-dynamo/vllm-runtime
  # @ignored
  pullPolicy: IfNotPresent
  # -- The vllm runtime image tag
  # @default -- The chart's appVersion
  tag: ""
  # -- The release of the custom OSC vllm runtime image
  release: "1"

# @ignored
podSecurityContext:
  runAsNonRoot: true

# @ignored
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
  drop:
  - ALL
  seccompProfile:
    type: RuntimeDefault
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

# @ignored
imagePuller:
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 128Mi
